### ISSUE TITLE
Mail stuff

### ISSUE THREAD

**Issue by jbcm627** [cubing/worldcubeassociation.org#1]
I don't know if we really want mail to work in the dev environment (we don't want test emails to actually send).  If we do, then installing PEAR could be useful.

**Comment by jfly** [comment]
PEAR is automatically configured in the production environment. See <https://github.com/cubing/worldcubeassociation.org/blob/2ef1853c6e783761a3ea52fb9bdfc97d01cf4131/chef/site-cookbooks/wca/recipes/default.rb#L260>.

We should still probably do something to make it more clear that we don't want test emails to send when in development mode. Possibly relevant: <https://github.com/cubing/worldcubeassociation.org/blob/master/chef/site-cookbooks/wca/templates/results_config.php.erb#L30>

**Comment by fw42** [comment]
https://github.com/ryanb/letter_opener is nice for this
