### ISSUE TITLE
Statistics page should use the latest name for a competitor

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#103]
On https://www.worldcubeassociation.org/results/statistics.php, Anthony Brooks shows up as Anthony Searle.

**Comment by jfly** [comment]
This should be a fun, easy project, but since the statistics page is currently in php, it will be throwaway work. Unless someone is excited to work on this, I'll let it wait until after we've ported everything to rails.

**Comment by pingskills** [comment]
Has this issue been fixed? Anthony is now showing up as Anthony Brooks?

**Comment by jfly** [comment]
Nope, I believe his name was changed in the database. Since this is a public repo, I'm actually going to remove him as an example and go ahead and close this issue.
