### ISSUE TITLE
Clean up `regulations` folder.

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#105]
- Remove references to `wca-documents-extra`.
- Move `announcements`, `doc`, and `style-guide.md` somewhere else.

**Comment by jfly** [comment]
Assigning to @viroulep as per @jonatanklosko's comment [here](https://github.com/cubing/worldcubeassociation.org/pull/747#issuecomment-229217530).

**Comment by viroulep** [comment]
Fixed in #747.
