### ISSUE TITLE
Move the Delegate crash course to the WCA website

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#119]
[link purposely omitted]

I think we should keep canonical documents on the WCA website. I think it would make sense to put the Delegate crash course on the website.
I think we can actually rewrite it a bit so that it's safe to make public.

Else, can we easily put a page behind Delegate access, @jfly?

**Comment by jfly** [comment]
Yeah, giving only delegates access to something is very doable.

**Comment by jfly** [comment]
This was done forever ago, lol. Closing.
