### ISSUE TITLE
Checkbox for showing competitors list is broken

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#126]
I just hit the "Update competition" button (I was hoping to get to a page to add the organizer), and it just automatically unchecked the "Show registered competitors on the WCA website".

Right now Pedro has given me the rights to edit the competition so I put it back.
When the issue occured I didn't have them, and the competition got edited to not display the list, so I assume it's not the intended behaviour.

**Comment by jfly** [comment]
Hmm... maybe I'm misunderstanding this. There are 2 checkboxes, "I would like to use the registration form on the WCA website." and "Show registered competitors on the WCA website.". Right now, if you deselect the first one, the second one is deselected: https://github.com/jfly/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/competitions_controller.rb#L227-229. Does it make sense to show a list of competitors if you're not using the registration form? Is this how you close registration for a competition?

**Comment by viroulep** [comment]
Yes it sure doesn't make sense, but this not what I meant at all :p 
Maybe I put it wrong, here is what I did : I clicked "Update competition" without modifying anything (both checkboxes were already checked), and it unchecked "show registered [...]".
