### ISSUE TITLE
Rss feed doesn't format markdown

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#127]
See https://www.worldcubeassociation.org/rss.xml and https://github.com/cubing/worldcubeassociation.org/pull/106. @timhabermaas, could you look into this? It should be a quick fix.

**Comment by timhabermaas** [comment]
What's the desired output? Unescaped XHTML within the `<description>` tags?

**Comment by jfly** [comment]
That's an good question. According to http://stackoverflow.com/a/10099772, we'd actually want escaped html. I'd test it out with an rss reader and verify that you get clickable links.
