### ISSUE TITLE
Google analytics!

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#13]
Gotta have it =)

**Comment by lgarron** [comment]
Do we? :-P

In particular, what are the main benefits we get over using the server logs?

**Comment by jfly** [comment]
We currently have it, so getting rid of it feels like a regression.

Not relying on server logs decouples us from our particular host, which is something I like. The simpler it is to spin up new servers, the happier I am.

**Comment by lgarron** [comment]
As far as I can tell, Dreamhost just outputs regular Apache logs. They certainly contain less immediately useful information than Google analytics, but I'm wondering whether we really need to take the privacy/performance hit of sending everything to Google, too.

If the answer is "it's convenient now, and we don't have time to run replacement analytics on our logs", that's fine, too.

**Comment by jfly** [comment]
Yeah, running analytics on the logs is yet another thing that would need to be done. We'd also need to back them up somewhere.

More importantly, I don't want to be tied into Apache. Once we've moved away from PHP, I intend to drop apache in favor of nginx + passenger, unicorn, or puma. This should give us a performance boost, in addition to simplifying developer setup.

**Comment by lgarron** [comment]
Those sound like solid reasons. Carry on. :-D
