### ISSUE TITLE
Port competition registration to rails

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#135]
- [x] We'll require that people register for competitions use a WCA website account.
  - [x] Users must fill in name, dob, gender, country before they can register
  - [x] Users cannot edit their "data" after they've registered for a competition, or if they already have a WCA id
- [x] We should make it possible for delegates to change people's name/nationality/birthday as well as WCA ids
- [x] We should make it impossible for users to change their name/nationality/birthday if they are already associated with a wca id.
- [x] Add a link to register from `competition.php`
- [x] Remove old php registration code
- [x] Port publicly viewable registered competitors list from PHP to rails
  - [x] Port psych sheet to rails
    - [x] Don't show position for people who have never competed, but do show the people
    - [x] Competition nav bar
      - [x] Nest edit stuff
        - [x] Badge with pending registration count
      - [x] Nest all psych sheets
      - [x] Sticky navbar
      - [x] Escaping map...
- [x] Don't show register page or link for competitions that aren't using WCA registration...
  - [x] Enforce this at the controller level
- [ ] Simplify `Preregs` schema #275
  - [x] Add index to ensure that `(competition_id, user_id)` are unique, or `user_id` is null.`
- [x] Allow approving a registration from the edit registration page

**Comment by SAuroux** [comment]
Do you also plan to automate WCA-ID association after a WCA account was
used to register for a competition?

2015-08-19 9:38 GMT+02:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
Yeah, although porting the results admin scripts will probably be one of the last things to get ported. See #21.
