### ISSUE TITLE
Delegate voting system

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#136]
(See discussion here: https://groups.google.com/d/msg/wca-software/ND7YeOs1EHk/C2Xe93h0AgAJ)

The WCA delegates mailing list is a pretty awful place to actually have a discussion, and it's really hard to come to a consensus on things.

Some thoughts copy pasted:

- Lucas: I'm going to push for this to be simple but flexible (e.g. radio/multiple choice with free-form text for comments on the vote).
- Laura: +1 for an open questions format for comments This could be really useful as a feedback system. E-Mail discussions become messy after a few replies ("I agree with x and y, but..."), so this could make collecting arguments/opinions a lot easier.
- Oliver: Had we had the system already, I would vote yes. ;)

The comment system could possibly be shared with a commenting system on the homepage (see #51)

**Comment by lgarron** [comment]
Personally, I'd be happy with something very similar to a simplified Google form, except that each person has a single set of responses that is 1) tied only to them, and 2) possible for them to edit until some deadline.
3) An edit history would be nice (at least available to website admins to see if there's funky behaviour going on), but not critical.

I strongly considered using a Google form mechanism for voting this year, but allowing each person to edit their responses (and only theirs) requires either giving them a URL with pre-filled responses, or requires them to record a URL when they're done. It also makes it a bit hard to tie votes (what do to) to justifications (why).

**Comment by jfly** [comment]
@pedrosino took care of this in #253
