### ISSUE TITLE
check_results.php doesn't need a recent feature, it just needs the ability to check a given competition

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#147]
This would be more in line with how the check_regional_record_markers script works.

**Comment by SAuroux** [comment]
For consistency with check_regional_record_markers.php, I would suggest to also add a dropdown with events.

**Comment by jfly** [comment]
What about removing the event dropdown in both places? That would also be consistent, and make the code simpler.

**Comment by SAuroux** [comment]
No! At least for the record marker script, this covers important use cases.
:)

2015-08-25 23:49 GMT+02:00 Jeremy Fleischman <notifications@github.com>:

**Comment by SAuroux** [comment]
I can imagine some for the other scripts as well.

2015-08-26 0:49 GMT+02:00 Sébastien Auroux <sebastien.auroux@gmx.net>:
