### ISSUE TITLE
Let admins edit mail adresses and delete accounts via the website interface

### ISSUE THREAD

**Issue by SAuroux** [cubing/worldcubeassociation.org#149]

**Comment by jfly** [comment]
I'm sure you've thought this through already, but for posterity, could you explain why we want this?

As mentioned elsewhere, I'm nervous about giving humans an easy way to delete accounts, and would be more OK with a merge two accounts and delete one feature, although it will be basically impossible to write that feature in a way such that people who add new features to the website know to update it. Any technical ideas for solving that problem are very welcome.

If the point of deleting accounts is to just keep things clean, I'd rather let a cron job take care of that.

As for editing emails, are we trying to deal with the case where people lose access to their email account? If so, how do we prove that the person requesting an email change is actually the correct person? There's a possibility of social hacking here.

**Comment by SAuroux** [comment]
Sorry, i was in a hurry when creating this issue. :)

Users can edit their own mail adresses, right? It is weird, that an admin cannot do the same.

As for deleting accounts, I am all open for senseful alternatives. The use case where I had to do that through the DB today was indeed merging two accounts.

**Comment by jfly** [comment]
When a user edits their email address, it doesn't actually change until they confirm the new email address (there's an `unconfirmed_email` field in the `users` table for the mean time). I'm just not sure what the best behavior is here. Should the same thing happen when an admin changes someone's email address?

Merging accounts is pretty scary. I don't know if you realized this, but this morning, you only updated the `competition_delegates` table, not the `competition_organizer` table when merging Dror's accounts. This sort of stuff will only get harder as we add more and more features to the WCA website. As I mentioned before, I can't think of a good way of writing a script to do this, either.

**Comment by pingskills** [comment]
@jfly @SAuroux is this still an issue or can it be closed?

**Comment by SAuroux** [comment]
Good question... 

@jfly has convincing arguments against admins changing mail addresses. 

As for deleting accounts, I currently fail to find a common use case where we still need this. So indeed this issue can probably be closed.

**Comment by jfly** [comment]
I agree! Let's close this.
