### ISSUE TITLE
Map of competitions for competitors is broken

### ISSUE THREAD

**Issue by Laura-O** [cubing/worldcubeassociation.org#159]
The map of competitions on the competitors page is not displayed ([Example](https://www.worldcubeassociation.org/results/person_map.php?i=2009OHRN01)).

Someone told me that it has been broken for several weeks. Maybe it would be better to remove the link if it does not have high priority at the moment?

**Comment by jfly** [comment]
My bad! I delete some files I thought were unused, but apparently they are still being used. That's a real bummer that this was broken for so long and we didn't know =(.
