### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#16]
Something unobtrusive like on https://live.cubing.net/ would be nice. Could point people to github. A potential layout:

```
Powered by [link to github] | Contact
```
or perhaps

```
Fork me on github! | Contact
```

or

```
&copy; World Cube Association | Contact | ... ?
```

is copywrite cheesy these days?

**Comment by FatBoyXPC** [comment]
I feel like putting a copyright symbol when we don't actually hold a copyright is certainly pretty cheesy. I like the fork me | contact option, or maybe say "Contribute" rather than "Fork".
