### ISSUE TITLE
/competitions page is awful

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#160]
It would probably make sense to combine it with the public facing competitions list.

**Comment by SAuroux** [comment]
it would also be great to include a convient way for the results team to get an overview if the results iof a competition are posted or not, in particular to check if certain results are late for a while. 

something like:
green: past and results
red: past and no results
grey: future

**Comment by jbcm627** [comment]
Closing this issue, more recent discussion in #438.
