### ISSUE TITLE
Delegates should be able to create competitions themselves, rather than first contacting the board

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#162]
See https://groups.google.com/d/msg/wca-software/DyqGILta208/g5qvidKYBgAJ for relevant discussion.

**Comment by SAuroux** [comment]
If this happens, we should definitely add another temporary database table.
I wouldn't like having a a lot of messed up competition creation attempts
in the Competitions table.
Am 02.09.2015 05:35 schrieb "Jeremy Fleischman" <notifications@github.com>:

**Comment by jfly** [comment]
From a software perspective, I don't think it makes sense to have a separate table for this. If we're worried about abandoned competitions, then we can periodically scrub competitions that were never announced and haven't been touched in a month.

**Comment by jfly** [comment]
It also might not make sense to do this until we've done #91, because we're going to want the board to assign the competition ID, and I don't think we can change the id with our current schema.
