### ISSUE TITLE
Fix links on regulation history page

### ISSUE THREAD

**Issue by Laura-O** [cubing/worldcubeassociation.org#169]
I just wanted to add the [2015 regulation changes](https://github.com/cubing/wca-regulations/compare/official-2014-04-03...official-2015-07-01#files_bucket) to the [regulation history page](https://www.worldcubeassociation.org/regulations/history/) but failed to find the link of the announcement  post with the summarized changes, so I couldn't add that. Any idea how to find it?

Furthermore, the links to the summarized changes of 2014 are broken as well.

**Comment by jfly** [comment]
Ran the following query:

```sql
select * from posts where posts.title LIKE '%regulations%'
```

![2015-09-14_2209x663_kaladin](https://cloud.githubusercontent.com/assets/277474/9856700/1b1044f6-5acb-11e5-9aec-c2a8cd898e43.png)

(we should probably add post searching support as part of #66.)

I think you're looking for https://www.worldcubeassociation.org/posts/wca-regulations-july-2015?

As for the broken links, is is possible you're looking for https://www.worldcubeassociation.org/posts/regulations-and-guidelines-april-3-2014 and https://www.worldcubeassociation.org/posts/wca-regulations-and-guidelines-2014?

**Comment by Laura-O** [comment]
Fixed in ac5819492fa4b9b4305a328ff83ccb49a98e610a
