### ISSUE TITLE
Additional validations when confirming a competition

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#179]
Right now, we aren't very strict about required fields when saving a competition, and I like that behavior. It allows someone to partially fill out the field, and just click save. @SAuroux suggested that we could be really strict about what you need to do before *confirming* a competition, however. That sounds like a great idea to me. Things we can be strict about:

- [x] competitions should have > 0 events
- [x] competition dates should be filled in
- [x] "Everything except 'Venue details' and 'Information' should be mandatory before confirming is possible in my opinion" -@SAuroux

@timhabermaas, any ideas for how to implement this? I was thinking our validations inside the Competition model could look at `if isConfirmed && !isConfirmed_was` and then do stricter validations.

**Comment by timhabermaas** [comment]
> I was thinking our validations inside the Competition model could look at `if isConfirmed && !isConfirmed_was` and then do stricter validations.

That sounds good to me.
