### ISSUE TITLE
When running `rails s` locally, everything's logged twice

### ISSUE THREAD

**Issue by timhabermaas** [cubing/worldcubeassociation.org#187]
```
I, [2015-10-05T23:12:30.325236 #18657]  INFO -- : Started GET "/statistics" for ::1 at 2015-10-05 23:12:30 +0200
I, [2015-10-05T23:12:30.325254 #18657]  INFO -- : Started GET "/statistics" for ::1 at 2015-10-05 23:12:30 +0200
I, [2015-10-05T23:12:30.334475 #18657]  INFO -- : Processing by StatisticsController#index as HTML
I, [2015-10-05T23:12:30.334519 #18657]  INFO -- : Processing by StatisticsController#index as HTML
D, [2015-10-05T23:12:31.282036 #18657] DEBUG -- :    (941.2ms)          SELECT
          personId,
          personName,
          count(pos=1 or null) gold,
          count(pos=2 or null) silver,
          count(pos=3 or null) bronze
        FROM Results
        WHERE roundId IN ('f', 'c') AND eventId='333'
        GROUP BY personId
        ORDER BY gold DESC, silver DESC, bronze DESC, personName
        LIMIT 10

D, [2015-10-05T23:12:31.282114 #18657] DEBUG -- :    (941.2ms)          SELECT
          personId,
          personName,
          count(pos=1 or null) gold,
          count(pos=2 or null) silver,
          count(pos=3 or null) bronze
        FROM Results
        WHERE roundId IN ('f', 'c') AND eventId='333'
        GROUP BY personId
        ORDER BY gold DESC, silver DESC, bronze DESC, personName
        LIMIT 10
```

The timings are exactly the same, so it's only a logging issue, not two threads running in parallel trying to answer the same request.

**Comment by jfly** [comment]
Wow, I cannot believe I never noticed this before! https://github.com/heroku/rails_stdout_logging/issues/1 seems to address this issue. I see this issue if I run `rails s`, but not if I run `rackup -p 3000`. https://github.com/heroku/rails_stdout_logging/issues/1#issuecomment-31359563 feels a bit gross to me, but is something we could try out.

**Comment by jfly** [comment]
Some light investigation:

```
$ bin/rails console
irb(main):030:0> ActiveRecord::Base.logger == Rails.application.config.logger
=> true
irb(main):031:0> ActiveRecord::Base.logger.info("foo")
foo
I, [2016-05-05T12:16:50.885742 #1197]  INFO -- : foo
=> true
irb(main):032:0> Logger.new(STDOUT).info("FOO")
I, [2016-05-05T12:17:01.893830 #1197]  INFO -- : FOO
=> true
irb(main):033:0> 
```

Notice how `ActiveRecord::Base.logger` and `Rails.application.config.logger` are the exact same Logger, which clearly double prints. A freshly instantiated Logger does not have this double printing behavior.

I'm going to dig into the current `ActiveRecord::Base.logger` and try to figure out why it's double printing.

**Comment by jfly** [comment]
Ok, I've found the source of the double logging in `bin/rails console`. See the following code from ActiveRecord (https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/railtie.rb#L61):

```ruby
    # When loading console, force ActiveRecord::Base to be loaded
    # to avoid cross references when loading a constant for the
    # first time. Also, make it output to STDERR.
    console do |app|
      require "active_record/railties/console_sandbox" if app.sandbox?
      require "active_record/base"
      console = ActiveSupport::Logger.new(STDERR)
      Rails.logger.extend ActiveSupport::Logger.broadcast console
    end
```

At the time this code runs, we already have a logger, so this gives us a second one we don't need.

I'm not sure yet why this works in a fresh Rails application. I'm also not sure if this explains the weirdness with `rails server` (this code appears to be specific to `rails console`).
