### ISSUE TITLE
Test wca-documents building Travis

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#195]
If it's too slow, perhaps only test when the `regulations` folder was modified?

**Comment by jfly** [comment]
I will accept a PR for this, although I am curious what the motivation behind this is. Are we trying to catch tool regressions? Or is it possible to change the regulations markdown in a way such that it will no longer compile?

**Comment by lgarron** [comment]
> Are we trying to catch tool regressions?

Yes.

> Or is it possible to change the regulations markdown in a way such that it will no longer compile?

Yes.

(The HTML generator checks for the number of sections in the Regulations and Guidelines, and fails if the number is not correct.)

**Comment by jfly** [comment]
> Also yes. 

> (The HTML generator checks for the number of sections in the Regulations and Guidelines, and fails if the number is not correct.)

I see. Will testing this in `cubing/worldcubeassociation.org` be useful so long at the regulations are actually in a [separate repository]([https://github.com/cubing/wca-regulations)?

**Comment by lgarron** [comment]
It depends on whether you want to draw the line at unit tests of integration tests. ;-)

**Comment by jfly** [comment]
Assigning to @viroulep as per his comment [here](https://github.com/cubing/worldcubeassociation.org/pull/747#issuecomment-229275357).

**Comment by viroulep** [comment]
Fixed in #747.
