### ISSUE TITLE
Add icons to the menu

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#198]
I always find it a bit confusing to navigate the Results menu.
Here are some mockups using [Font Awesome](http://fontawesome.io/icons/)

<img width="207" alt="screen shot 2015-10-16 at 13 30 16" src="https://cloud.githubusercontent.com/assets/248078/10552640/12d4662a-740a-11e5-8622-0dc0d6c72da2.png">
<img width="191" alt="screen shot 2015-10-16 at 13 30 18" src="https://cloud.githubusercontent.com/assets/248078/10552645/15883fd6-740a-11e5-921a-1200ee4f21ba.png">
<img width="234" alt="screen shot 2015-10-16 at 13 30 06" src="https://cloud.githubusercontent.com/assets/248078/10552659/2de55780-740a-11e5-954e-06b3c9a8b8fc.png">

**Comment by jfly** [comment]
These seem nice to me. Since you've already picked out icons, can we discuss this in a pull request?

**Comment by lgarron** [comment]
Sure; the actual code is trivial, but I'd need to figure out how to include Font Awesome.

**Comment by jfly** [comment]
Sounds good. The directions on http://fortawesome.github.io/Font-Awesome/get-started/ point to https://github.com/FortAwesome/font-awesome-sass, which looks trivial enough.

**Comment by lgarron** [comment]
Oh, yes, I've used Font Awesome before. I'm just not very familiar with our own CSS structure. :-P

**Comment by jfly** [comment]
Well, we're all railsy now, so I meant specifically the directions [here](https://github.com/FortAwesome/font-awesome-sass#a-ruby-on-rails).

**Comment by lgarron** [comment]
Ooh, cool. Will do "soon".

**Comment by jfly** [comment]
Cheers! Thanks @lgarron!
