### ISSUE TITLE
Remove "Miscellaneous" menu item from Competitions

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#199]
Place the stats links on the statistics page.
(The database export already has its own menu item.)

**Comment by jfly** [comment]
Can you explain this? Where's this "Miscellaneous" menu item?

**Comment by lgarron** [comment]
I see that you already don't miss it. ;-)

Fixed in 8662813a942ed6b4102ec3b1fbf0cb66fb3feeca.
(It was a link to https://www.worldcubeassociation.org/results/misc.php between "Multimedia" and "Database Export".)

**Comment by SAuroux** [comment]
Hey Lucas,

so how can one reach the content of this site now? I cannot find it on the
website (except the database export of course).

2015-10-21 0:11 GMT+02:00 Lucas Garron <notifications@github.com>:

**Comment by SAuroux** [comment]
Or more specifically: you mentioned putting the stat links on the
statistics page, but they are not there.

2015-10-21 0:59 GMT+02:00 Sébastien Auroux <sebastien.auroux@gmx.net>:

**Comment by lgarron** [comment]
They should be on the [statistics page](https://www.worldcubeassociation.org/results/statistics.php), but it appears this did not get regenerated in production. How do I force a regeneration?

**Comment by lgarron** [comment]
> How do I force a regeneration?

Never mind, I found it.

**Comment by jfly** [comment]
For posterity, Lucas found the update_statistics_page link in
https://www.worldcubeassociation.org/results/admin/.

**Comment by lgarron** [comment]
(And by the way, the links are on the statistics page now.)

**Comment by SAuroux** [comment]
Oh, I should have tried updating the statistics before asking. :)
Am 21.10.2015 02:08 schrieb "Lucas Garron" <notifications@github.com>:
