### ISSUE TITLE
Investigate additional results admin scripts to run while provisioning VM

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#2]
We currently automatically generate auxiliary data in [setup_db_interactive.sh](https://github.com/cubing/worldcubeassociation.org/blob/master/setup_db_interactive.sh#L29). @jbcm627 pointed out that we're probably missing a few:

     James:  other pages might need generating too (stats, export, ...)

**Comment by lgarron** [comment]
We should make sure we have them clearly categorized as "run at setup, and regularly thereafter" vs. normal provisioning scripts ("run only at setup", e.g. database creation).

**Comment by jfly** [comment]
This has been cleaned up a good bit. We now have scripts with a clear CLI here: https://github.com/cubing/worldcubeassociation.org/tree/master/scripts, and results.sh has a `rebuild()` method specifically for running these "additional results admin scripts": https://github.com/cubing/worldcubeassociation.org/blob/master/scripts/results.sh#L93
