### ISSUE TITLE
Our responsive header has weird intermediate layouts for some viewport widths

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#210]
In particular, everything between the extreme ends:

![screen shot 2015-11-05 at 12 39 35](https://cloud.githubusercontent.com/assets/248078/10982205/cfbec170-83c0-11e5-8868-b51921f05734.png)
![screen shot 2015-11-05 at 12 39 38](https://cloud.githubusercontent.com/assets/248078/10982206/d0a959b0-83c0-11e5-9e33-988f04b0ace7.png)
![screen shot 2015-11-05 at 12 39 51](https://cloud.githubusercontent.com/assets/248078/10982221/e260b39c-83c0-11e5-8968-311d47a7fb03.png)
![screen shot 2015-11-05 at 12 39 41](https://cloud.githubusercontent.com/assets/248078/10982212/d4692f6c-83c0-11e5-9c27-657904e176e8.png)
![screen shot 2015-11-05 at 12 39 49](https://cloud.githubusercontent.com/assets/248078/10982213/d5a2a0c0-83c0-11e5-82f2-2c688a470a70.png)

**Comment by lgarron** [comment]
Looks very nice!

**Comment by jfly** [comment]
Thanks! It's live now.

**Comment by lgarron** [comment]
Yeah, I've been playing with it.

There seems to be a regression: hovering over the menu items does not show the dropdown.
