### ISSUE TITLE
Change "Rankings" menu icon

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#211]
Oliver commented that he doesn't like that the current icon (`fa-signal`) looks like a WiFi symbol.
My original second preference was [`list-ol`](http://fortawesome.github.io/Font-Awesome/icon/list-ol/); I'd be happy to switch.

**Comment by jfly** [comment]
Can we rotate the current one (wifi signal) 90 degrees?

**Comment by lgarron** [comment]
> Can we rotate the current one (wifi signal) 90 degrees?

I'd slightly prefer this, as it avoids duplicating the overall menu icon. But I don't feel strongly.

**Comment by operge** [comment]
If it would be possible, I'd prefer a tiny podium icon. :)

**Comment by lgarron** [comment]
90 degree rotation example: <img width="225" alt="screen shot 2015-11-05 at 13 40 00" src="https://cloud.githubusercontent.com/assets/248078/10982543/bb70d6ca-83c2-11e5-825e-56977af37839.png">

**Comment by lgarron** [comment]
> If it would be possible, I'd prefer a tiny podium icon. :)

To me, podium suggests "best", i.e. record-holders. I think I would prefer something that indicates general ranking to distinguish it from `Records`.

**Comment by jfly** [comment]
Thanks for the example screenshot. I think that looks great!

**Comment by operge** [comment]
> Thanks for the example screenshot. I think that looks great!

Agreed, it is much better. Thanks!

**Comment by lgarron** [comment]
Alright, I agree, it looks better at 90 degrees. I'll just go ahead and make the change, since it's so simple.

**Comment by lgarron** [comment]
The change is live.

**Comment by jfly** [comment]
LGTM, thanks Lucas!
