### ISSUE TITLE
Allow archive.org to crawl

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#215]
<https://web.archive.org/web/*/worldcubeassociation.org> says:

> Page cannot be crawled or displayed due to robots.txt.

**Comment by jfly** [comment]
Good catch @lgarron! I got the logic backwards in 0a6c5f304cf8677d4fbbaa01f5ce26bbcda299ee.

**Comment by jfly** [comment]
Actually, I'm reopening this issue. @lgarron, can you verify that https://www.worldcubeassociation.org/robots.txt looks good, and close this issue once https://web.archive.org/web/*/worldcubeassociation.org show signs of life?

**Comment by lgarron** [comment]
Indexed again!
https://web.archive.org/web/20150611005946/https://www.worldcubeassociation.org/
