### ISSUE TITLE
Have delegates upload their reports to the WCA website

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#222]
(Ilkyoo just asked for this. This is something I know @FatBoyXPC has been wanting for a while.)

This would just be a simple form where a delegate fills out some sections, and clicks submit. We'd store the report in our database, and automatically send an email to delegates@

Once we know if delegates have submitted their reports, we can bug them if they're late to submit their report.

See #483 with fancy ideas for future improvements.

**Comment by jfly** [comment]
One proposed structure: https://groups.google.com/forum/#!msg/wca-delegates/uidGkG9D1B4/ml_qGutBbmoJ

Also: https://docs.google.com/document/d/1UKkJY0cAsODjHo89s1G4AIRcn5Ui4jEVC8L-MZ9BNCw/edit

**Comment by viroulep** [comment]
Copying feedback from @Claster:

> Feature request:
> It is nice to have the number of competitors computed automatically. It would be also interesting to calculate the number of newcomers (this statistic can shed some light on a background of the competition and on the development of the speedcubing in this country), and maybe the number of registrations (if WCA website was used for that).

Statistics about that shouldn't be that hard, for newcomers we would probably have to go through every competitor and check if their number of competitions is 1. For registrations we have this pretty easily.


> Small remark:
> If a delegate enters a URL with a schedule without protocol (e.g. "cubecomps.com/live.php?cid=xxx" instead of "http://cubecomps.com/live.php?cid=xxx"), the protocol won't be added and the schedule link will lead to a wrong URL on the WCA website. Then, of course, one could say that a delegate should not forget to specify the protocol.

Could we add a default "http://" if the url doesn't start with either this or "https://"?

**Comment by FatBoyXPC** [comment]
I think the right answer here is to force protocol on input validation. We
have no way of knowing which protocol a 3rd party uses.

**Comment by TimMcMahon** [comment]
Could "new" competitors be calculated? It might be nice to record how many registered vs. how many competed too.

Is the schedule URL optional (schedule is missing)? Could we upload schedules to the WCA site like Cubecomps instead?

I usually press TAB to skip to the next input field when filling out forms but this caused a line to be indented and highlighted. It seems like GitHub hates tabs and prefers spaces. :-P

A +/- data entry feature for incidents with auto-numbering, instead of rich text, might make it easier to track and comment on particular issues. They could then be escalated to the WRC/WDC for review individually.

Numbers are lost when copy/pasting stuff into the rich text fields. You can't just select 10 lines and hit the "ordered list" button to prefix each line with a number that increments to 10, it makes all of them 1's. You need to type, hit enter to go to the next line for "2." to appear etc.

How do you want to handle multiple reports for Asian Champs, World Champs, Euros etc where there may be a handful of delegates providing reports?

**Comment by Laura-O** [comment]
* If you are not familiar with Markdown you probably do not understand how the image tag works. If that is possible, it would be nice to have a default text here, like "add your description here".

* In the preview the headings and the input text have the same font size. So you cannot distinguish between them if your text starts with bold letters (and I am sure people will do that).

* Automatically calculating statistics might be nice, but this requires that the WCA website was used for registration and the results were already posted, so I don't think that has a high priority now.

**Comment by jfly** [comment]
> Could we add a default "http://" if the url doesn't start with either this or "https://"?

> Is the schedule URL optional (schedule is missing)? Could we upload schedules to the WCA site like Cubecomps instead?

I've added validations for the schedule url and the discussion url. They must start with http:// or https:// and cannot contain spaces. Granted, this isn't perfect, but...

Schedules are very important for the results team to do their job. To apply 9i2, you need to know what day the round in question took place on. @Nikhil, IMO it's very bad that schedules from past competitions can disappear. Eventually, we'd like to store schedule information in the WCA database, but I'm not going to let that block this feature.


> Could "new" competitors be calculated? It might be nice to record how many registered vs. how many competed too.

Yes, although I'm not going to be doing that as part of this deploy. See https://github.com/cubing/worldcubeassociation.org/issues/483.


> I usually press TAB to skip to the next input field when filling out forms but this caused a line to be indented and highlighted. It seems like GitHub hates tabs and prefers spaces. :-P

I'm not sure what this has to do with GitHub, but I've fixed this for both tab and shift-tab. See [here](https://github.com/NextStepWebs/simplemde-markdown-editor/issues/122) and [here](https://github.com/jfly/worldcubeassociation.org/commit/8b603a5c84eebd7922468b2f1c38e5dfc77911ef).


> A +/- data entry feature for incidents with auto-numbering, instead of rich text, might make it easier to track and comment on particular issues. They could then be escalated to the WRC/WDC for review individually.

> Numbers are lost when copy/pasting stuff into the rich text fields. You can't just select 10 lines and hit the "ordered list" button to prefix each line with a number that increments to 10, it makes all of them 1's. You need to type, hit enter to go to the next line for "2." to appear etc.

I've added these notes to https://github.com/cubing/worldcubeassociation.org/issues/483.


> How do you want to handle multiple reports for Asian Champs, World Champs, Euros etc where there may be a handful of delegates providing reports?

All the delegates for a competition have access to this form, and any of them can submit it, causing their name to show up at the bottom:

![image](https://cloud.githubusercontent.com/assets/277474/15786778/53024b08-2973-11e6-9f67-6cfc7f2ec399.png)

We also include a list of all delegates and organizers:

![image](https://cloud.githubusercontent.com/assets/277474/15786784/5da7909a-2973-11e6-96d5-97bd0681c9c5.png)


> "Post" doesn't seem to save any updates made.

@TimMcMahon, I just tested editing and posting, and it seems to work. Perhaps you ran into the bug I just fixed where the "organisation" field wasn't being persisted?


> If you are not familiar with Markdown you probably do not understand how the image tag works. If that is possible, it would be nice to have a default text here, like "add your description here".

Good idea! I've added "Image description", so it's shorter and therefor easier to delete and replace with the actual description.

> In the preview the headings and the input text have the same font size. So you cannot distinguish between them if your text starts with bold letters (and I am sure people will do that).

@Laura-O, I'm afraid I don't understand this. I'm not entirely sure what "bold letters" means. Could you include a screenshot explaining what you mean?

**Comment by Laura-O** [comment]
Here is a minimal example:
![bildschirmfoto 2016-06-04 um 12 50 13](https://cloud.githubusercontent.com/assets/362249/15799134/ecb597b6-2a52-11e6-881a-648920eaa9f5.png)

If the Delegate adds subheadings to the text and makes them bold, it's not easy to identify the individual paragraphs. There seems to be a small gap between the heading and the text (between "Venue" and "room" in the screenshot), but could we make that a bit larger and/or change the font size of the default paragraphs (Equipment, Venue, etc.)?
