### ISSUE TITLE
I'm able to confirm a competition without a delegate

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#240]
Working on this...

**Comment by pedrosino** [comment]
I added :delegates to https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition.rb#L37.
The error is shown at the beginning, but the label doesn't turn red...couldn't find the definition for the validates method.

(Is this a problem only at my local environment, because I'm logged as a results team member?)

**Comment by jfly** [comment]
I would suspect that the `presence` validation isn't going to make any sense for the `delegates` field, as it's not a real field, but a helper method to access the `competition_delegates` join table. I'd suggest copying the [`must_have_at_least_one_event`](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition.rb#L40-L45) validation, it looks like it does almost exactly what you want.

**Comment by pedrosino** [comment]
I wonder what the 'EventSpecs' message is there...
I added a validation and used :delegates instead, but it looks weird to me to say: 
"Delegates Competition must have at least one delegate"

**Comment by jfly** [comment]
The error when you try to confirm a competition with no events:

![2015-11-23_821x138_kaladin](https://cloud.githubusercontent.com/assets/277474/11353771/08349fa0-91fb-11e5-8540-68684eff00f8.png)

**Comment by jfly** [comment]
It seems like http://stackoverflow.com/questions/5808611/customize-error-message-with-simple-form or http://stackoverflow.com/questions/808547/fully-custom-validation-error-message-with-rails show how to customize the rails generated error messages. It would also be nice to highlight the events red when non are selected.
