### ISSUE TITLE
Make error messages cleaner when confirming a competition

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#243]
Right now it looks weird for events and delegates:

![2015-11-23-221433_531x262_scrot](https://cloud.githubusercontent.com/assets/1881933/11354042/bce87938-922f-11e5-8265-558577f29f69.png)

**Comment by jfly** [comment]
The start date and end date messages look funky too!

**Comment by jfly** [comment]
See https://github.com/cubing/worldcubeassociation.org/issues/240#issuecomment-159109735 for possible way to fix this.
