### ISSUE TITLE
Internationalization of the website

### ISSUE THREAD

**Issue by gagou9** [cubing/worldcubeassociation.org#246]
Hello!

I was thinking that we could have the wca website in many languages instead of only english.

Would that make sense ? 
@jfly : I don't know how hard localization would be, whether texts are hardcoded or not...

**Comment by timhabermaas** [comment]
> whether texts are hardcoded or not...

They are.

IMO it's not worth the effort right now:

a) No one wants to maintain different translations over time
b) The website uses very basic English (except for the regulations which are already translated into different languages) and should therefore be understandable by basically everyone.

**Comment by jfly** [comment]
I think @timhabermaas speaks wisely here. It's not like we're going to ask our delegates to fill out competition information in many languages. We also have posts that are all in English.

I'm going to close this issue. @gagou9, if you feel strongly about this, can you start a discussion on software@? We're going to need reasons why this is worth doing, and someone willing to lead the charge (probably not me, sorry).

**Comment by gagou9** [comment]
I do agree :)

(sorry for bumping these issues up...)
