### ISSUE TITLE
Website without JS

### ISSUE THREAD

**Issue by gagou9** [cubing/worldcubeassociation.org#247]
Is it imaginable to have the website working without JS at some point ? Such as logging-in or so! It's currently not possible to login without JS!

Not sure this is really an issue, but more and more people are disabling JS to have leightweighter browsing and less tracking, as I do, so I was wondering...

**Comment by jfly** [comment]
At which point do you need JS to log in?

This is not something I'm motivated to work on, since I *do* run with JS enabled. I will accept PRs that make things degrade nicely, however. I'm going to close this issue, though. Feel free to work on anything you're motivated to work on!

**Comment by gagou9** [comment]
Yeah, I know I'm just saying things but doing nothing. Sorry about that, I am involved in many other projects now. Hard to keep working on everything!
So, about the JS, the mouseover thing doesn't work without JS, so that makes the Sign In button inaccessible. But yeah, don't worry about that.
