### ISSUE TITLE
Better information about waiting lists

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#250]
From Daniel Sheppard:

> Some sort of information about waiting lists. Maybe a flag can be set by organisers to say "Registration full, but can register for waiting list" and display that message clearly at the top of the registration form or something. Also display the number of people waiting already. I find that competitors often either don't realise that they will be going to a waiting list, or that they can still register even when the number of registrations matches the advertised limit.

- [x] Show competitor their status on the waiting list on the `/register` page. #250

**Comment by jbcm627** [comment]
CubingUSA doesn't do waiting lists. I think this has been done by hand in the past, @timreyn might have had to do this before?

**Comment by timreyn** [comment]
Nope, I've never done this.

**Comment by Baiqiang** [comment]
Cubing China doesn't do this either.
