### ISSUE TITLE
Some regulations guidelines are invisible

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#251]
See https://www.worldcubeassociation.org/regulations/guidelines.html#8a4++

![2015-11-30_1965x326_kaladin](https://cloud.githubusercontent.com/assets/277474/11484181/7dd15b98-9761-11e5-9d30-098813f182f5.png)

This is happening when these things are not wrapped inside of an anchor tag. Anchor tags are orange, which overrides bootstrap's `label` rules, which makes them white.

@lgarron, can you take this on?

**Comment by viroulep** [comment]
Just noticed that, @Luis-J-Ianez opened the same issue in cubing/wca-regulations#308.

This occurs when the "SEPARATE" label is used, indicating that the regulation a guideline refers to doesn't exist anymore.
I'll open a PR.

**Comment by jfly** [comment]
Thanks @viroulep! I've assigned the issue to you.
