### ISSUE TITLE
Change links colors?

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#261]
I was playing around and almost by accident tried this:
![2015-12-08-220422_669x661_scrot](https://cloud.githubusercontent.com/assets/1881933/11672857/22afbe58-9dfb-11e5-8260-9152792ec578.png)

Looks good to me, and easier on the eye than the orange...

**Comment by jfly** [comment]
I agree that it's easier on the eye. @lgarron, as far as I'm concerned, you're our only designer. What do you think?

**Comment by lgarron** [comment]
Our worst contrast on the front page (orange on gray) is [2.2](http://leaverou.github.io/contrast-ratio/#%23f60-on-%23ddd).
Our orange on white is [2.9](http://leaverou.github.io/contrast-ratio/#%23f60-on-%23fff).

The rule of thumb is that we should aim for at least 3, and 4.5 is best.
I don't entirely like the idea of replacing all our link colors with blue, because the orange text has been a distinctive part for the WCA website for a long time.

How about something a bit more red, like `#E64503`?
(Contrast of 4 on white text, 3 on gray.)

![screen shot 2015-12-08 at 17 03 59](https://cloud.githubusercontent.com/assets/248078/11673429/b53b1b88-9dcd-11e5-9e89-9f0d93afaf01.png)

**Comment by pedrosino** [comment]
The red looks very similar to orange for me...

#06a gives 6 on white and 4.4 on #ddd :)

**Comment by lgarron** [comment]
> The red looks very similar to orange for me...

That's the idea. I tried to find a color that looked similar but had enough contrast. ;-)

**Comment by lgarron** [comment]
One idea I took with [timer.cubing.net](http://timer.cubing.net/) (and have used on competition websites, originally from Shelley) is to pick a random color.

![screen shot 2015-12-08 at 17 10 09](https://cloud.githubusercontent.com/assets/248078/11673591/061ce54e-9dcf-11e5-9631-f680df18a5d3.png)
![screen shot 2015-12-08 at 17 10 24](https://cloud.githubusercontent.com/assets/248078/11673594/062313e2-9dcf-11e5-86dd-c443dfd9c839.png)
![screen shot 2015-12-08 at 17 14 11](https://cloud.githubusercontent.com/assets/248078/11673611/21ec82d4-9dcf-11e5-8caa-0d3d0e9b49f3.png)
![screen shot 2015-12-08 at 17 13 04](https://cloud.githubusercontent.com/assets/248078/11673592/06200e36-9dcf-11e5-8eb1-486662573720.png)

**Comment by pedrosino** [comment]
I'm working on the competitions index page, and planning to use font-size: 12px;

I'm using #e9e9e9 as background for the table-striped, and the orange doesn't look good to me with the smaller font...

![2016-01-16-181548_1169x485_scrot](https://cloud.githubusercontent.com/assets/1881933/12374263/309c85fa-bc7d-11e5-9f5c-6233e745cadd.png)

**Comment by lgarron** [comment]
> I'm using #e9e9e9 as background for the table-striped, and the orange doesn't look good to me with the smaller font...

What if you use `#E64503` for the orange, per https://github.com/cubing/worldcubeassociation.org/issues/261#issuecomment-163074131?

**Comment by pedrosino** [comment]
A little better:
![2016-01-17-115334_1187x408_scrot](https://cloud.githubusercontent.com/assets/1881933/12377798/faabf7e8-bd10-11e5-932c-565a92b53258.png)

(was like this)
![2016-01-16-181840_1172x407_scrot](https://cloud.githubusercontent.com/assets/1881933/12377795/e04e86b8-bd10-11e5-9b71-cd945c1cfc88.png)

**Comment by pingskills** [comment]
@pedrosino where did you get to with this issue? It sounds like some good ideas were discussed.

**Comment by pedrosino** [comment]
I don't remember...lol

I think the striped colors were changed, but not the links.
You can make a PR or I can do it...

**Comment by pingskills** [comment]
lol. I'm happy for you to do it. I was just going through the issues and thought I'd ask how some old ones were going :)
