### ISSUE TITLE
Missing stuff for polls system

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#262]
- [x] Link to polls index at results and vote
- [x] Show which option you voted for at results
- [x] Show which polls you already voted at index
- [x] Make it clear that you are editing your vote
- [x] Save multiple votes
- [x] Load multiple votes
- [x] Edit multiple votes (currently calls action 'create' instead of update)
- [x] Markdown?
- [x] Only show "confirmed" polls (similar to competitions)
- [x] Check if polls have options
- [x] No deleting or editing options after confirming
- [x] Allow (only) deadline to change after confirming
- [x] Maxlength for options (this is kinda buggy...f.input doesn't style correctly, so I used f.text_field, which requires a maxlength property)
- [x] Redirect to editing after updating
- [x] Merge radio buttons and check boxes code
- [x] Check if option belongs to that poll
- [x] Show open and closed polls in separate lists/tables

- [x] Change votes_controller
- [x] Add extra text field to polls

- [x] Add link to vote on edit page
- [x] Delete a poll

- [x] Show local time at vote
- [x] Make it clear that poll deadline is UTC

**Comment by jfly** [comment]
A nice solution for making it clear that you're editing your vote might be to disable the whole form until the user clicks a big fat "Edit" button on the page. It seems find to me to This could be implemented in pure javascript.

**Comment by jfly** [comment]
Being able to edit options after confirming seems just as bad as being able to delete options. Do we trust the pollers not to be rigging the vote?

**Comment by pedrosino** [comment]
Yeah, editing should not be allowed too.

**Comment by pedrosino** [comment]
@jfly I think adding a "Edit" button is clumsy, since we already have a "Edit vote" link on the index page.
I just added a warning saying that you already voted and can edit your vote below.

**Comment by pedrosino** [comment]
I think I've checked all boxes here!

Will try to write some tests...

**Comment by jfly** [comment]
Markdown is super easy, check out how posts work [here](https://github.com/jfly/worldcubeassociation.org/blob/055a993f8724ea27084dc303485ad1a809d2857b/WcaOnRails/app/views/posts/_post.html.erb#L29).

**Comment by pedrosino** [comment]
How about using it for radio button labels too? 
<%=md f.input :poll_option_id, label: false, collection: @poll.poll_options, as: :radio_buttons, label_method: lambda { |c| c.description }, value_method: lambda { |c| c.id } %>
doesn't work

**Comment by jfly** [comment]
Does it work if you try to use markdown for the actual label, rather than the entire `f.input`? Something like:

```ruby
<%= f.input :poll_option_id, label: false, collection: @poll.poll_options, as: :radio_buttons, label_method: lambda { |c| md c.description }, value_method: lambda { |c| c.id } %>
```

**Comment by pedrosino** [comment]
Yes, it does :)
