### ISSUE TITLE
Do we prefer "WCA id", or "WCA ID"?

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#268]
I think both are certainly better than "WCA Id", which is what Rails gives us by default. I made the decision to go with "WCA id", but never talked to anyone about it. My thinking was that "WCA ID" felt a bit too... loud. @patriciali feels that "WCA id" looks weird, but I am too far down the rabbit hole to have opinions on this anymore.

I thought it would be good to have a discussion, and pick something to standardize on. @lgarron, @pochmann, @jbcm627, @FatBoyXPC, any opinions here?

**Comment by FatBoyXPC** [comment]
I vote for ID.

**Comment by lgarron** [comment]
ID as an abbreviation is usually uppercase. "WCA ID" is the only way that looks correct to me.

(I think the main time it's appropriate to use lowercase is for *code* or consistency with other abbreviations in the same context. But I don't think these apply here.)

**Comment by lgarron** [comment]
If you're bothered about the lack of separation, we could make "WCA-ID" a thing, though.

**Comment by jfly** [comment]
Seems like the consensus is "WCA ID" over "WCA id". I've gone ahead and made that change on our entire codebase. Hopefully I didn't miss any!
