### ISSUE TITLE
Letting competitors edit their own registrations?

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#269]
Right now, we just tell them to contact the organizer.

We should think about what options organizers need, vs what makes sense for everyone and doesn't need an option. I'm sure @jbcm627, @Baiqiang, and @pedrosino have thought about this a lot in cusa, cubingchina, and the Brazilian registration system.

**Comment by pedrosino** [comment]
I allow competitors to log in and edit their registration, with the same form as a new registration.

Seems to work good, and with RoR it should be a piece of cake.

**Comment by jfly** [comment]
This is superceded by #417 and #418.
