### ISSUE TITLE
Poll results don't handle the case where nobody voted

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#271]
See this code https://github.com/cubing/worldcubeassociation.org/blob/3b4ba0e510a81068e6af9a3a0875061a5587cd29/WcaOnRails/app/views/polls/results.html.erb#L21:

```ruby
          <% option_percentage = (option.vote_options.count.to_f/@poll.votes.count*100).round(2) %>
```

If `@poll.votes.count` is 0, then we end up dividing by 0...

@pedrosino, can you fix this cosmetic bug? I think the best thing to do is to add an `percentage` method to `PollOption`.

**Comment by pedrosino** [comment]
Fixed this and also added a check on wether the poll is closed on the edit page.
