### ISSUE TITLE
Add worldcubeassociation.org to the HSTS preload list.

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#28]
1. Add the token `preload` to the `Strict-Transport-Security` header.
2. Submit `worldcubeassociation.org` (not `www.worldcubeassociation.org`) to https://hstspreload.appspot.com/

This is easy to do, but I've put it on hold due to Jeremy's work.

**Comment by jfly** [comment]
Great. Thanks for making a note of this.

**Comment by jfly** [comment]
@lgarron, I believe that things are now in a state where we can do this. Please assign this to yourself if you can take this on.

**Comment by lgarron** [comment]
Could we make sure the header is also served from `worldcubeassociation.org`?
It is currently not:

    $ curl -I https://worldcubeassociation.org
    HTTP/1.1 301 Moved Permanently
    Server: nginx/1.8.0
    Date: Tue, 02 Jun 2015 21:41:17 GMT
    Content-Type: text/html
    Content-Length: 184
    Connection: keep-alive
    Location: https://www.worldcubeassociation.org/

**Comment by jfly** [comment]
Updated chef scripts and pushed.


```bash
curl -I https://worldcubeassociation.org
HTTP/1.1 301 Moved Permanently
Server: nginx/1.8.0
Date: Tue, 02 Jun 2015 22:01:19 GMT
Content-Type: text/html
Content-Length: 184
Connection: keep-alive
Location: https://www.worldcubeassociation.org/
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
```

**Comment by gagou9** [comment]
We are on the preload list : https://code.google.com/p/chromium/codesearch#chromium/src/net/http/transport_security_state_static.json&l=2850
