### ISSUE TITLE
Remove bootstrap-datepicker-rails in favor of datetimepicker-rails

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#281]
I believe we're only using it for the competition start and end dates in a fancy date range thing.

**Comment by pedrosino** [comment]
Maybe close this? :)

**Comment by jfly** [comment]
Yep! This (and a bunch of other issues) will automatically close when #280 is merged up. See:

![2015-12-31_1280x130_kaladin](https://cloud.githubusercontent.com/assets/277474/12066926/3bb7220e-afa5-11e5-8c64-8b92e0144837.png)
