### ISSUE TITLE
Redirect back to /register page after logging in

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#283]
Urg... <https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update> looks promising, but work. @timhabermaas, do you have any suggestions for how to give someone a sign in link that brings them back to the page they were just on?

**Comment by timhabermaas** [comment]
Mhh, shouldn't this work out of the box with devise? https://github.com/plataformatec/devise/blob/280d12b81cbb15796188a6b6c00dc9658a3f6961/lib/devise/controllers/helpers.rb#L214 grabs the stored location if it exists and the location is being stored in the [`FailureApp`](https://github.com/plataformatec/devise/blob/dd5de829c944dd955e4b35074c60798c3ad4b947/lib/devise/failure_app.rb#L79). I'm not sure why this isn't working.

If you build authentication from scratch that's also pretty much how you'd do it yourself: Store a session with the current path if the user is about to be redirected to the sign in page.

**Comment by jfly** [comment]
Yeah, the problem here is that I built a page that looks like this: 

![2015-12-30_1248x414_kaladin](https://cloud.githubusercontent.com/assets/277474/12060810/65c843b2-af2c-11e5-8ec6-30bfb298c03a.png "/register when not logged in")

See that "Log in" link? Before or after clicking that link, none of the code in `FailureApp` runs. I created a new route: `/register-require-sign-in` that *does* have a `before_action` that requires you to be logged in. You can see this [here](https://github.com/jfly/worldcubeassociation.org/commit/ce0ec3827eb80041d08d98a5c3e67a9aafc71f5e). Kind of hacky, but it works.
