### ISSUE TITLE
Option to turn off the guest box

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#286]
From Daniel Sheppard:

> One suggestion - option to turn off the "guest" box. Not an essential feature, but at our competitions we never need names of guests, and we get people filling that out in detail and then emailing us later to alter their guests or worried that they're not sure about the number of guests they're bringing.

@jbcm627, @Baiqiang, @pedrosino, how do your systems handle this?

**Comment by Baiqiang** [comment]
Cubing China doesn't has the "guest" box.

**Comment by pedrosino** [comment]
I don't have it either :P
Em 31/12/2015 07:25, "Baiqiang" <notifications@github.com> escreveu:

**Comment by jfly** [comment]
I agree it doesn't seem too useful as is. @jbcm627, am I correct in thinking that CUSA only asks for a number of guests? Here are the settings I see:

![2015-12-31_1202x281_kaladin](https://cloud.githubusercontent.com/assets/277474/12068438/05b75a7a-afc3-11e5-8311-8e9d03e814ce.png)
