### ISSUE TITLE
Update competition_delegates table when changing a competition Id

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#287]
I found this by accident today, with Sebastién.

If I search for Fangyuan's competitions in 2015, I can do it 2 ways:
1 - select RIGHT(competition_id,4) = '2015'
2 - select Competitions.year = '2015'

But they were giving different results. By comparing the lists, I found that there is a 'BeijingLongEvents2015' and a 'BeijingLongEventsOpen2015' in the competition_delegates table, but only the first one is actually a competition.

My guess is that the id was changed after the competition being created, and the outdated line was never erased from competition_delegates.

@jfly

**Comment by pedrosino** [comment]
See #288

**Comment by SAuroux** [comment]
Thanks for making this issue Pedro.

Once this is fixed, we should clean up the competition_delegates and
competition_organizers tables. I suppose the following queries should do
the job:

DELETE FROM `competition_delegates` WHERE competition_id not in (SELECT id
from Competitions);
DELETE FROM `competition_organizers` WHERE competition_id not in (SELECT id
from Competitions)

Currently there are 33 such rows for the delegates table and 28 for the
organizers table. Or do we need to be careful here? Is it possible that
these rows are still linked with something else?

2015-12-31 14:33 GMT+01:00 pedrosino <notifications@github.com>:

**Comment by jfly** [comment]
I've pushed a fix for this live, with Pedro's help. @SAuroux, those 33 + 28 rows are fine to delete, which I've gone ahead and done. Closing this issue.

**Comment by SAuroux** [comment]
great, thank you. :)

2016-01-01 3:10 GMT+01:00 Jeremy Fleischman <notifications@github.com>:
