### ISSUE TITLE
Give organizers and delegates a list of (upcoming?) competitions they're organizing

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#293]
Oleg and Raúl have both asked for this.

Raúl:

> As an organizer I miss a shortcut to manage my competitions, currently I just click in the registration emails to go there. A link under "edit profile" would be nice, or a "Manage competition" in the competition page if you are logged in.

I personally think our "edit profile" page is getting pretty cluttered, and would rather put this somewhere else, but I'm not sure where to put it. I think a navbar dropdown under our current Competitions tab might look good:

![image](https://cloud.githubusercontent.com/assets/277474/12084886/08404b6e-b26e-11e5-9731-cec4778742a7.png)

(ignore the icons)
But I can't think of what text to put there! I fear "My Competitions" isn't clear about if it's competitions I've been too, or competitions I've organized/organizing.

**Comment by jfly** [comment]
In a similar vein (also requested by Raúl), competitors should be able to easily get to a list of upcoming competitions they've registered for.

**Comment by pedrosino** [comment]
By 'edit your profile' you mean this: 
![2016-01-05-200506_302x578_scrot](https://cloud.githubusercontent.com/assets/1881933/12128945/ab6084ba-b3e7-11e5-993f-d2835f9c52f4.png)
?

I agree that is crowded for delegates probably, but for competitors it's not too bad, I guess.
I thought maybe this "My competitions" (or whatever) could be next to the Regulations link. It would only appear if you are logged in.

**Comment by jfly** [comment]
I don't think we have space for yet another button on the navbar, which is why I suggested putting it as a dropdown underneath Competitions.

**Comment by pedrosino** [comment]
I'm working on this...

**Comment by pedrosino** [comment]
I'll make a list of ideas we had so far:
[ ] Show only upcoming competitions
[ ] Show all competitions in a single list*
[ ] Link to manage registrations
[ ] Differentiate visible/invisible (opacity?) and confirmed/unconfirmed (colors?)

* a delegate has 3 "types" of competitions: delegating, organizing, competing. And one competition can fit all 3 types at once.

**Comment by pedrosino** [comment]
![2016-01-07-115151_1180x383_scrot](https://cloud.githubusercontent.com/assets/1881933/12171979/11ce7c0e-b535-11e5-98ed-0fd9e6023198.png)
This is how it looks like.

**Comment by pedrosino** [comment]
Added a link to edit the competition (on the competition name) if you're the delegate or organizer, and the "Registration" link only appears in that condition too 
![2016-01-07-142806_1176x409_scrot](https://cloud.githubusercontent.com/assets/1881933/12175711/e34c60ce-b54a-11e5-968c-70e6712bf475.png)

![2016-01-07-142701_1192x242_scrot](https://cloud.githubusercontent.com/assets/1881933/12175734/fe0aff74-b54a-11e5-9143-9ea64efa7df0.png)

If you're only a competitor, you'll see no links
![2016-01-07-143241_1190x213_scrot](https://cloud.githubusercontent.com/assets/1881933/12175836/87736fa8-b54b-11e5-9f37-f5793090c532.png)

**Comment by jfly** [comment]
Yes, definitely have the name link to the competition homepage, and add an edit link somewhere at the end, please!

**Comment by pedrosino** [comment]
Ok, I've changed it.

**Comment by pedrosino** [comment]
If I update my PR with "Fixes #293", will it close this?

**Comment by jfly** [comment]
Closed!
