### ISSUE TITLE
Regulations files that are not in git

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#3]
The following folders exist only on the WCA website (and backups):

```
./history/files/ => Copies of old regs and scramblers
./history/official => Old versions of regs manually placed here and linked from https://www.worldcubeassociation.org/regulations/history/
./scrambles/tnoodle (and ./scrambles/tnoodle/old) => TNoodle binaries
```

In the interest of one step deploy and development setup, I'd like to think about what our options are for these files. @lgarron says "I don't care what we do with them, as long as we don't lose them. I would prefer not to put them in a general repo, because it adds up to > 60MB." I agree that this is a painful amount of data to add to just any repo. @lgarron, how do you feel about yet another branch on [cubing/wca-documents](https://github.com/cubing/wca-documents)? I'd be willing to drive this and update [make.py](https://github.com/cubing/wca-documents-extra/blob/master/make.py) to automatically check out these files.

**Comment by lgarron** [comment]
For now, I'd prefer `wca-documents` to stay purely dedicated to the text of the Regulations. (Each branch only has textual changes – or translations.)

I would suggest a new branch on cubing/wca-documents-extra , or a general `data` branch in this repo.

**Comment by jfly** [comment]
A new branch on `cubing/wca-documents-extra` sounds nice to me (I'd rather not have wca-documents-extra know anything about this repo (worldcubeassociation.org), just seems cleaner to me to not have a dependency cycle). I'll investigate this today. Do you have any preference for branch name? Does a general `data` branch on wca-documents-extra sound good?

I just noticed https://github.com/blog/1986-announcing-git-large-file-storage-lfs today. Do you have any knowledge about it?

**Comment by lgarron** [comment]
A `data` branch sounds good. I'd go for a branch instead of something else fancy for now (even if it makes wca-documents-extra slow by default).

**Comment by jfly** [comment]
Sounds great! Git clone doesn't bring down branches other than master by default, right?

**Comment by lgarron** [comment]
> Sounds great! Git clone doesn't bring down branches other than master by default, right?

Uh, very false?
I haven't checked in a while, but I'm pretty sure it brings all branches.

**Comment by lgarron** [comment]
[Yeah](https://git-scm.herokuapp.com/docs/git-clone):

> Clones a repository into a newly created directory, creates remote-tracking branches for each branch in the cloned repository

**Comment by jfly** [comment]
Interesting. I have some fundamental gaps in my knowledge of how git works. I thought that all data is stored in the .git folder, but it's only 17MB in a fresh clone, when we have 50+ MB of stuff in our data branch...

```bash
~/tmp @kaladin> git clone git@github.com:cubing/wca-documents-extra.git w2
~/tmp @kaladin> cd w2
~/tmp/w2 @kaladin> git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
~/tmp/w2 @kaladin> git branch
* master
~/tmp/w2 @kaladin> du -h w2
...
18M	.
~/tmp/w2 @kaladin> git fetch origin data:data
From github.com:cubing/wca-documents-extra
 * [new branch]      data       -> data
~/tmp/w2 @kaladin> git branch
  data
* master
~/tmp/w2 @kaladin> du . -h
~/tmp/w2 @kaladin> git checkout data
Switched to branch 'data'
~/tmp/w2 @kaladin> du . -h
...
80M	.
~/tmp/w2 @kaladin> git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
~/tmp/w2 @kaladin> du . -h
...
18M	.
```

Anyways, looks like you're right.

**Comment by jfly** [comment]
If we're willing to suffer the consequences of a painful initial `git clone`, why not commit these files into `wca-documents-extra` directly, instead of in a new branch?

**Comment by lgarron** [comment]
Because that doesn't let us change our mind about where to put the files without amending history. ;-)

**Comment by jfly** [comment]
Closing this as it has been dealt with =)
