### ISSUE TITLE
Port competitions.php to Rails

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#300]
- https://www.worldcubeassociation.org/results/competitions.php?eventId=&regionId=_Africa&years=current&pattern=&list=List
- https://www.worldcubeassociation.org/results/competitions.php?eventId=&regionId=_Africa&years=current&pattern=&map=Map

Misc ideas:
- [ ] I think the behavior of ["current"](https://github.com/jfly/worldcubeassociation.org/blob/cf48ec334ea70637f9ec82f95acb78b6aad8a3af/webroot/results/includes/_framework.php#L166-L168) on this page is very confusing, and believe that this would be a good opportunity to clean it up.
- [ ] The colors are also pretty confusing. I think it would be clearer to have a link directly to registration rather than a random color.
- [x] Nginx redirects from the old php routes to the new rails routes -@FatBoyXPC

**Comment by FatBoyXPC** [comment]
nginx redirects!

**Comment by pedrosino** [comment]
I agree about the colors, but I'd like to somehow separate past from upcoming competitions.

What don't  you like about "current"? You think it should be "the present calendar year"? I tend to agree with that

**Comment by pedrosino** [comment]
What would be the desired behavior?
Do we want to show competitions only for the current calendar year?
Do we want to show competitions like (today-6 months) to (today+6 months)?
Or maybe (farthest_comp_date) - 1 year?

I'll try to work a bit on this.

**Comment by jfly** [comment]
@lgarron, will changing this page affect http://www.cubing.net/cal/wca.ics?

**Comment by lgarron** [comment]
Probably. But it's third-party, so I guess you're welcome to break it. ;-)

**Comment by lgarron** [comment]
If you want to provide a subscribable calendar on the WCA website, it should be really easy. The format is about as straightforward as it gets:

https://github.com/lgarron/wca_ical/blob/2594dd483ce4c68c1c71b7d0488531edaf6ebafd/wca_competition_feed.php#L170

**Comment by pedrosino** [comment]
This is what it looks so far.
![2016-01-11-133408_1185x313_scrot](https://cloud.githubusercontent.com/assets/1881933/12237851/02af0d8e-b868-11e5-805e-20c4b842f3a1.png)

Not sure about the best way to separate future and past competitions (and results/no-results too?)

**Comment by jfly** [comment]
As we discussed earlier, I think have a nice obvious "today"  in the table might be a cool way to separate past/present.

How about adding an additional link directly to results? That would make it obvious if results have been uploaded.

**Comment by pedrosino** [comment]
This leads to another discussion: what will be the "new /results/c.php..." page be like?
Currently results are posted there, so the same link leads to the "competition page" and to the "competition results page". 
Will it stay that way? Are we separating those?

**Comment by jfly** [comment]
Good question. I'm working on that right now, and decided to maintain the current solution of showing the winners on that page. I have created separate routes for the top3, all, and by_person views, however. How about a link directly to all results, rather than just the winners?

**Comment by pedrosino** [comment]
Will all of those be linked at the "c.php" page?
I like the way it is now, with everything in the same place...

**Comment by jfly** [comment]
Yeah, it's all going onto the new competition sidebar.

**Comment by pedrosino** [comment]
Some screenshots
This is what it currently looks like:
![2016-01-16-181840_1172x407_scrot](https://cloud.githubusercontent.com/assets/1881933/12374276/c4391a76-bc7d-11e5-8da8-5959cd2ed305.png)

This is an idea I had
![2016-01-16-181820_1224x412_scrot](https://cloud.githubusercontent.com/assets/1881933/12374277/cd0acb9a-bc7d-11e5-84e9-f5733919a714.png)
(blue = #139, green = #173)

And one with same link colors, but a "today" mark (looks kinda dumb, but you can get the idea)
![2016-01-16-182734_1168x409_scrot](https://cloud.githubusercontent.com/assets/1881933/12374316/d94212e6-bc7e-11e5-9f5b-9acf187cf643.png)

**Comment by jfly** [comment]
All of those look good to me, Pedro! I am particularly looking forward to a "today" row =)

**Comment by pedrosino** [comment]
I decided to combine both. The "today" line uses bootstrap's info style, and past competitions have blue links.

**Comment by pedrosino** [comment]
It should be up on https://staging.worldcubeassociation.org/ if anyone wants to take a look.

**Comment by jbcm627** [comment]
Alternative layout idea for the list of competitions:
http://www.bootply.com/Clx4vCiyOT

**Comment by jfly** [comment]
Oh *damn*, I really like Jim's cardlike layout, it looks particularly mobile friendly. It does look like it needs some `white-space: nowrap`:

![2016-02-21_582x310_kaladin](https://cloud.githubusercontent.com/assets/277474/13209731/3c44ad12-d8dc-11e5-87da-8de218f3d43c.png)

**Comment by jbcm627** [comment]
Tweaked that on the demo, and combined the date columns too.
http://www.bootply.com/Q9VcNyZ6fo

It may look funny when the one column is empty, which can happen when filtering by year. It might need to revert to a wider column or something different in that case.
