### ISSUE TITLE
Port persons.php to Rails

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#304]
See https://www.worldcubeassociation.org/results/persons.php.

I'd like to add this functionality to https://www.worldcubeassociation.org/search somehow. I don't think there's any value in the Event dropdown, and I'm not sure that the Region dropdown really serves any purpose either.

![2016-01-05_1858x187_kaladin](https://cloud.githubusercontent.com/assets/277474/12133331/39e2b960-b3d9-11e5-9ca7-fffe97321225.png)

**Comment by pedrosino** [comment]
I think region is useful when you're searching for a common name, and know the person is in Asia and not Europe, for example.

Agreed about the event, doesn't seem useful at all.

**Comment by jfly** [comment]
The search does already look for people, but it doesn't allow filtering by region. I'm not sure how to fit that into the UI. Also, our existing search limits the results to only 10 or 15 people, whereas the PHP person search shows all matching people, which can be pretty nice. I don't even show up in the first page of results when you [search for jeremy](https://www.worldcubeassociation.org/search?q=jeremy) =(.
