### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#307]
It is not 100% informative now.

- [ ] Tell people that the default password is 'wca' in the test world.
- [ ] Instructions on how to run it locally without vagrant (bundle install --deployment may be needed)

**Comment by viroulep** [comment]
Just found this very useful issue.

When running in vagrant, is there a specific command to run after getting upstream changes (I'm thinking updating db schema, installing potential new gems and stuff) ?
Is `vagrant provision` enough ?

**Comment by jfly** [comment]
We started https://github.com/cubing/worldcubeassociation.org/wiki/Misc.-important-commands-to-know as a dumping ground for useful commands to run when inside Vagrant, but it's by no means polished or comprehensive. I'm very open to improving the documentation here, but I think it would be best if someone who doesn't know the codebase as well as me were to push on that =)

**Comment by viroulep** [comment]
I've updated the wiki page with the notes I took during my digging in the internals, could one please take a look at it ?

**Comment by jfly** [comment]
@viroulep, the updated wiki looks awesome, thank you!! One note: a less destructive way to run tests is to specify a different database to run your tests against. I've updated the wiki (see https://github.com/cubing/worldcubeassociation.org/wiki/Misc.-important-commands-to-know#running-tests-and-filling-the-database) to reflect this. I didn't test out the commands though, big apologies if they don't actually work!

**Comment by jfly** [comment]
I'm going to close this issue for now, but please feel free to reopen it if there is other stuff we want to remember to add.

**Comment by viroulep** [comment]
> One note: a less destructive way to run tests is to specify a different database to run your tests against.

Nice !
Commands work :)

One thing I don't actually know how to do and which probably would be good to add is how to directly access the database. Is there a phpmyadmin or something equivalent in this setup ? (Or even just a prompt)

**Comment by timhabermaas** [comment]
Is `mysql -u root -p secret cubing` what you're looking for?

**Comment by viroulep** [comment]
That's it, thanks ! I'm dumb.
(the default db setup doesn't appear to have a root password though, so `mysql cubing` is actually enough)

**Comment by jfly** [comment]
There's also phpMyAdmin if you want a gooey. Log in as software_team and look at the links in the dropdown at the top right. There should be a phpMyAdmin link in there.
