### ISSUE TITLE
No upcoming competitions is sad looking =(

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#310]
See:

![2016-01-08_2070x319_kaladin](https://cloud.githubusercontent.com/assets/277474/12214612/99cbccf8-b650-11e5-952b-5f3122b8d39d.png)

@pedrosino, how about a friendly message here?

**Comment by pedrosino** [comment]
Also, as requested by Ming:
"One question here I got is, can the non-latin characters be shown instead of the question mark?"
Ming Zheng (??) appears instead of Ming Zheng (郑鸣)

**Comment by pedrosino** [comment]
How do we close this? It was solved on #313

**Comment by jfly** [comment]
If your commit messages say stuff like "fixes #123", the  you don't need to close issues by hand.

**Comment by pedrosino** [comment]
It said "Fixes #309 and #310"
Guess github.com is not *that* smart.

**Comment by FatBoyXPC** [comment]
Might need to say "Fixes #309 an fixes #310"
