### ISSUE TITLE
Notify people when results from a competition they participated in are uploaded

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#311]
We could even congratulate them on PBs and give them neat statistics like "congratulations on your nth competition/nth solve/whatever else might be fun".

Do we think this would this be annoying or cool?

**Comment by pedrosino** [comment]
I think it would be cool.

How about competitions which don't use the WCA registration and/or people who don't have an account?

**Comment by jfly** [comment]
It doesn't matter if the competition used the wca registration system, all that matters is if competitors have an account. There's not much of anything we can do for people without accounts.

**Comment by jfly** [comment]
@jonatanklosko did this a while back. Closing.
