### ISSUE TITLE
Improvements to registration flow

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#317]
@Luis-J-Ianez did some field research on how well our new registration system works, and the results are... depressing. Here are some of Luis's thoughts for improving this:

So here you are my two main conclusions:

- [x] First off, the [Sign up] link is exasperatingly hidden.
  - When you're not signed in, the account menu should include [Sign up] apart from [Sign in] and [Didn't receive confirmation email?]
- [ ] Definitely, I think that translating all the pages related to accessing the accounts system is something that we will regret not to do. (#289)
  - I didn't assist my friend at first (intentionally :P ) and let him try and find the things on his own.  Well, apart that he was unable to 'see' the [sign up] link, later I had the feeling that he wasn't familiar enough to the creation of an account process, and this joined to the fact that he was not able to understand English, made me realize that setting up accounts in the new webpage is a real, big problem for some of our visitors.

**Comment by pingskills** [comment]
@jfly can this issue be closed now? Is it covered by #289?

**Comment by jfly** [comment]
Yeah, closing this in favor of #289.
