### ISSUE TITLE
Changes to solve_time.rb require restarting the server in development mode

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#324]
This is quite confusing and annoying. Before I start to dig, @timhabermaas, do you know anything about this?

**Comment by timhabermaas** [comment]
Adding `lib` to `config.autoload_paths` in `application.rb` probably fixes this:

`config.autoload_paths << Rails.root.join('lib')`

This will require you to adhere to Rails' class naming convention, though. (`foo.rb` -> `class Foo`/`module Foo`)

You can check the currently autoloaded folders in the rails console: `ActiveSupport::Dependencies.autoload_paths`

**Comment by jfly** [comment]
That works, thanks! Any idea why `/lib` was removed from the autoload_paths? The internet says this used to be part of rails, but was removed in Rails 3.something.

**Comment by timhabermaas** [comment]
@jfly Did you reopen this by mistake? I believe this is fixed.

**Comment by jfly** [comment]
Whoops! Closing.
