### ISSUE TITLE
Preregs.user_id is not updated when an account is created

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#326]
We recently added a new delegate, and he told me he is registered for a competition, but it doesn't appear under My Competitions.

I checked the Preregs table and his registration is there, including the WCA id, but the user_id field is NULL. In fact, it is NULL for everybody in that particular comp (OxenteOpen2016).

My guess is that once someone creates an account, their user id is never assigned to the old registrations.
Is this fixable?

**Comment by timhabermaas** [comment]
What's the purpose of that redundancy in the first place (`user_id` AND `personId` in the preregs table)? Just `personId` should be enough, shouldn't it?

**Comment by pedrosino** [comment]
Well, personId is the WCA id from Results.
Not everybody who competed has a user_id (and most never will have), so the separation makes sense, I guess, so we can keep old data.

**Comment by timhabermaas** [comment]
>Not everybody who competed has a user_id (and most never will have), so the separation makes sense

You can always get to the user through the `personId`, couldn't you? Having `user_id` and `personId` might make sense if we allow users who haven't competed yet to pre-register. But `personId` can't be `NULL`, so we don't allow this, do we?

**Comment by pedrosino** [comment]
Well, someone who never competed before won't have a personId, and those should of course be allowed to register. The not NULL doesn't make sense here...

@jfly do you know why this is like this?

**Comment by jfly** [comment]
The old php registration system had no concept of accounts, and instead stored all the user's information in the rows of Preregs.

Under the new system, we require people to register with a wca website account, so user_id will always be filled in. However, there are still tons of rows for old competitions, and some for upcoming competitions whose registration opened before the new rails registration system went live. After all these upcoming competitions are over, I want to have a discussion about how valuable all that old user_id-less registration information is. Depending on how we feel about it, we could just delete all old registrations and remove all the extra columns, or we could create a new simpler table, and rename the current table in a way that makes it obvious it's not being used for anything. 

Pedro, you are correct that we don't update the Preregs table when user accounts are created (technically speaking, we should probably wait to do this until accounts are confirmed). How would you expect to identify old registrations, though? Would you check for matching email addresses?

I'm not sure this is really worth the effort to fix, however,  as this problem will naturally go away in a few months when there are no longer any upcoming competitions that used the old registration system.

**Comment by jfly** [comment]
Also, see https://github.com/cubing/worldcubeassociation.org/issues/275

**Comment by pingskills** [comment]
@jfly I think this issue has probably gone away and be closed since everyone will be using the new registration system now.

**Comment by jfly** [comment]
Absolutely correct, Jeff!
