### ISSUE TITLE
Move away from table-for

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#331]
Performance seems to be pretty bad =(. I'm also not pleased with how messy the `wca_table_for` method has gotten.

**Comment by pedrosino** [comment]
Already did my part on this :)

**Comment by jfly** [comment]
This is so bad that https://www.worldcubeassociation.org/competitions/ShaastraCubeOpen2016/registrations won't even load, but instead times out after 30 seconds.
