### ISSUE TITLE
Building the regulations locally

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#334]
Hi guys,

is there a way to build the regulations locally without the whole VM ?

I've built and ran the website with vagrant without the regulations, and now it's setting up the full version.
Using vagrant consumes a bit of time and a whole lot of hard drive space for dependencies I probably already have on my system, so I figured I would test the "local" way meanwhile.

There is few instructions on command to run in the readme, but by following what is done in travis I managed to build the website locally, but it does not include the regulations (I ran `bundle exec rake2.2` which I believe started the test process, and `rails server` to set the server up).
Any way I could build the regulations with that ?
Also when I opened the local version there was not all the dummy posts as in the vagrant build, did I missed something or should I populate the database beforehand ?

I remember that before wca-documents were merged I could run `make.py` to just build the regulations, I've noticed the script is still there but it doesn't work anymore (which is not that surprising given everything's changed :p).

Any help will be much appreciated !

**Comment by jfly** [comment]
@viroulep, check out https://github.com/cubing/worldcubeassociation.org/blob/0d2f5690fd99fd97136d33f0276887b420b10dcf/scripts/deploy.sh#L13. That's the command to rebuild the regulations. Building the regulations requires a lot of painful dependencies, which you can find most of here: https://github.com/cubing/worldcubeassociation.org/blob/0d2f5690fd99fd97136d33f0276887b420b10dcf/chef/site-cookbooks/wca/recipes/regulations.rb.

I'm closing this issue, feel free to reopen or hit me up on gchat if you have further questions.

**Comment by viroulep** [comment]
Thank you for the pointer to the scripts !
I was actually running the right thing previously, but I thought the failure was on me, turns out it fails to build with pandoc >=1.14, so I'm re-opening this (the vagrant image has 1.12, I have 1.15).

I ran into an issue that other experienced when pandoc introduced the `\tightlist` command in list, see this : https://github.com/rstudio/rmarkdown/issues/439, and this in the pandoc repo : https://github.com/jgm/pandoc/pull/1571.

The fix is pretty simple as you can just add the correct definition in the basic latex template in pdf.py : 
```latex
\providecommand{\tightlist}{
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
```

The regulations fully build with this and continue to work in the vagrant environment.
I'm not sure if you want to fix a non-issue in the production environment, but if at some point you want to upgrade the system image it may be nice to have this in mind.


That being said, I can run the server with the regulations so I have what I want :)

FYI I also encountered a weird encoding error when trying to download any regulations' pdf from the generated website :

```
ActionView::WrongEncodingError at /regulations/translations/french/wca-regulations-and-guidelines.pdf
Your template was not saved as valid UTF-8. Please either specify UTF-8 as the encoding for your template in your text editor, or mark the template with its encoding by inserting the following as the first line of the template:

# encoding: <name of correct encoding>.
```
The same happens for the original regulations, and all the translations I tested.
Unless you have an idea about where it could be coming from, or unless you do want me to investigate this, I'm just going to ignore this and assumes something is wrong in my environment.
It doesn't happen in vagrant and as the generated pdfs are ok.

**Comment by jfly** [comment]
Thanks for the investigation! I don't know much about latex, but if you think it's the right thing to do, please send a PR with the change to the tightlist command.

I'm not sure I understand the WrongEncodingError you're running into. Is this specifically when running rails locally without Vagrant?

**Comment by viroulep** [comment]
Ok I'll do it !
I think it's the right thing to do **if** at some point you'll upgrade the environment, or if you want to support building in recent ubuntu/debian distribution ;)

For the encoding it's indeed when I'm running locally, the html version of the regulations is displayed correctly, but as soon as I try to download a pdf I get this :
![wrong-encoding](https://cloud.githubusercontent.com/assets/1007485/12436794/ab12575e-bf18-11e5-9355-46adb179f63e.png)

**Comment by jfly** [comment]
I imagine we'll move off of Ubuntu 14.04 once it's no longer LTS. As I understand it, 14.04 is the most recent version of Ubuntu that is LTS: https://wiki.ubuntu.com/LTS.

See https://github.com/jfly/worldcubeassociation.org/blob/master/chef/site-cookbooks/wca/templates/worldcubeassociation.org.conf.erb#L167-L174 for why the PDFs aren't working on plain old Rails. It might be possible to configure Rails to serve them up correctly, but it would only be useful in development, as we let nginx handle them in production.

**Comment by viroulep** [comment]
Ah ah not that soon then :p

Thanks for the pdf explanation !
