### ISSUE TITLE
One of "My competitions" doesn't show up

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#335]
Hey,

I didn't noticed at first but I have an issue with the "My competitions" page : I can see the FMC europe for which I'm a delegate in my upcoming competitions, but not the "Open Cube Project" which uses the WCA registration system, and for which I'm already registered (before this feature was introduced).

Bug ?

**Comment by timhabermaas** [comment]
This might be the same issue as described in https://github.com/cubing/worldcubeassociation.org/issues/326.

**Comment by jfly** [comment]
This is definitely the same as #326:

```SQL
SQL query: SELECT id, competitionId, personId, user_id FROM Preregs WHERE Preregs.personId="2008VIRO01" ORDER BY id DESC LIMIT 0, 25 ;
Rows: 25

id	competitionId	personId	user_id
84831	OpenCubeProject2016	2008VIRO01	NULL
82954	UgineJeuetJouet2015	2008VIRO01	NULL
...
```

Note that the `user_id` field is NULL.

Closing this issue.
