### ISSUE TITLE
About the signature of automated competition mails

### ISSUE THREAD

**Issue by SAuroux** [cubing/worldcubeassociation.org#337]
After being listed as second delegate for Zonhoven Open 2016, I noticed that the competition acceptance mails are signed by both organizer and delegate automatically. I find this a very weird behaviour, since the delegate has generally nothing to do with the pre-registration process of a competition. It also suggests, that the delegate is also in charge of the competition's organization, which is not necessarily the case. So I would prefer to only list the names of the organizers there.

**Comment by jfly** [comment]
Fixing this is as simple as changing this line of code: https://github.com/cubing/worldcubeassociation.org/blob/0d2f5690fd99fd97136d33f0276887b420b10dcf/WcaOnRails/app/views/registrations_mailer/notify_registrant_of_new_registration.html.erb#L18 from:

```ruby
  Regards, <%= competition.managers.map(&:name).sort.to_sentence %>.
```

to:

```ruby
  Regards, <%= competition.organizers.map(&:name).sort.to_sentence %>.
```

**Comment by pingskills** [comment]
It seems we can have a competition without organizers. Does this happen in reality? Should I perform a check to see if there are no organizers and then use delegates? Or should we make it mandatory to have at least one organizer?

**Comment by pedrosino** [comment]
Competitions without organizers (listed on the website) are rather common, mostly because they don't have an account. I don't think making it mandatory is valuable.

**Comment by jfly** [comment]
Ah, good catch, Jeff! In that case, I'm not sure what to do here. @SAuroux, what do you think? Use organizers if there are any, otherwise use delegates?

**Comment by pingskills** [comment]
Hi @SAuroux, do have any thoughts on how to approach this?

**Comment by SAuroux** [comment]
Sorry, I missed the first reference by Jeremy.

I agree to use only the organizers if available. Technically, if there are
no organizers listed, there should be noone signing. But using the
delegates as a fallback is fine for me as well.

2016-05-29 11:54 GMT+02:00 Jeff Plumb <notifications@github.com>:

**Comment by pingskills** [comment]
Do we want the reply email address to still include the delegates or should the email only come from the organizers?

**Comment by SAuroux** [comment]
Organizers only in my opinion. In general, a delegate should not be
required to deal with such basic organizational stuff. If he wants to do
so, he can just be an organizer in addition. :)

2016-05-30 14:38 GMT+02:00 Jeff Plumb <notifications@github.com>:

**Comment by pingskills** [comment]
Deployed.
