### ISSUE TITLE
FloatThead versus hidden tables

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#343]
Looks like they don't like each other. Try the "My competitions" link.

![2016-01-21_1535x472_kaladin](https://cloud.githubusercontent.com/assets/277474/12499843/e9df2fb6-c062-11e5-95b8-ae10dddbc542.png)

**Comment by mkoryak** [comment]
if you init the plugin on a hidden table, you need to trigger the `reflow` event when the table becomes visible.

**Comment by jfly** [comment]
Thanks @mkoryak! @pedrosino, can you take this on?

**Comment by pedrosino** [comment]
Oh, this was already fixed.
But apparently it doesn't work too well on mobile.

**Comment by mkoryak** [comment]
you shouldnt use that plugin on mobile. it requires a modern CPU :P

**Comment by pedrosino** [comment]
Ha! Sadly I have no idea about developing on mobile :(

Let me try to find something...

**Comment by mkoryak** [comment]
use the user agent string to detect mobile browsers, or maybe there is a lib out there that already does this, then just dont init the plugin on mobile

**Comment by mkoryak** [comment]
if you change your code to do this:
```js
       $('#past-competitions').on('show.bs.collapse', function(e) {
         $('#past-competitions table:not(.floatThead-table)').trigger('reflow');
       });
```
then it will continue to work even if the plugin was not initialized

**Comment by pedrosino** [comment]
https://github.com/fnando/browser

Does that sound good?

**Comment by mkoryak** [comment]
thats a rails thing, detecting that stuff can be done in js. im not sure you want that whole giant rails thing just to turn off one plugin.. on the other hand, it probably works really well and wont make your stuff load any slower

**Comment by pedrosino** [comment]
>var $tablesToFloatHeaders = $('table.floatThead');
>  if (detectmob()) {
>    $tablesToFloatHeaders.floatThead({
>      zIndex: 999, // Allow bootstrap popups (z-index 1000) to show up on top.
>    });
>    // Workaround for https://github.com/mkoryak/floatThead/issues/263
>    $tablesToFloatHeaders.each(function() {
>      var $table = $(this);
>      $table.closest('.table-responsive').scroll(function(e) {
>        $table.floatThead('reflow');
>      });
>    });
>    alert('mobile');
 > } else {
 >   alert('not mobile');
 > }

I've added this check (detecmob() returns true or false if the browser is mobile), but it still floats on mobile...Is there something else we need to stop?
