### ISSUE TITLE
Why do we have 2 container divs?

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#344]
One of them is empty...
However, if I remove the div from the .html.erb files, it doesn't work.

**Comment by jfly** [comment]
See https://github.com/cubing/worldcubeassociation.org/blob/6bfa236f22863a1242871663aada9511ea2075a7/WcaOnRails/app/views/layouts/_flash.html.erb#L1. We create a `div.container` for all our flash messages.

There's a tradeoff between repeating ourselves and flexibility here. I chose to have application.html.erb *not* create the div.container for views. This gives views the flexibility to create a div.container-fluid, for instance. However, there are ways around that particular problem (using content_for and yield), and I'm not sure we're using the potential flexibility anywhere else.

One place where it would come useful is if we decide we wanted to add sub navbars, as bootstrap navbars must exist outside of a div.container.

**Comment by jfly** [comment]
I'm going to declare this a design thing I don't have a super strong opinion about, and am going to close this. If people have opinions about a better way of handling this, lets definitely reopen this and have a discussion.
