### ISSUE TITLE
Bug in checkSimilarResults()

### ISSUE THREAD

**Issue by Luis-J-Ianez** [cubing/worldcubeassociation.org#347]
This function inside `webroot/results/admin/check_results.php` includes a stupid bug of mine.  It detects duplicates from different persons in the same event or different events, but not from a person in different events.  Line 340 says

    AND Results.personId < h.personId

and it should say

    AND (Results.eventId <> h.eventId OR Results.personId < h.personId)

**Comment by Luis-J-Ianez** [comment]
In fact, wouldn't it be better 

    AND Results.id <> h.id

that simple...?

**Comment by jfly** [comment]
I like the `AND Results.id <> h.id` suggestion!
