### ISSUE TITLE
Specify what kind of input is allowed in the contact field

### ISSUE THREAD

**Issue by jbcm627** [cubing/worldcubeassociation.org#348]
https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/edit.html.erb#L242
Right now it looks like I can use HTML to create a link to a CubingUSA website contact form. Maybe we should restrict allowed tags (same for other fields), or allow only markdown or something? (Or are tags restricted already?)

**Comment by jfly** [comment]
It's still the crazy `[{...}{...}]` syntax, but it will change to markdown once #332 is merged up, where *did* add a message about what is supported: https://github.com/cubing/worldcubeassociation.org/pull/332/files#diff-94edf8bc77a69940d1816d5bc8485d96R244.
