### ISSUE TITLE
Underscore.js vs lodash.js?

### ISSUE THREAD

**Issue by timhabermaas** [cubing/worldcubeassociation.org#355]
Why do we have both in https://github.com/cubing/worldcubeassociation.org/blob/4c7263bbb55ac40b9cd774e5b4fa7a1f4b03c4e3/WcaOnRails/app/assets/javascripts/application.js? They are basically the same library, according to some blog posts lodash is a superset of underscore. They even use the same top level object (`_`), so including both just leads to one of them overriding the other.

**Comment by jfly** [comment]
Wow, that's bad! We define lodash second, so it probably would work to remove the underscore gem and remove the import from application.js.

**Comment by jfly** [comment]
Assigning to myself so I remember to look at this, but @timhabermaas, feel free to assign this to yourself if you have free cycles. I see you gave it the label polish-serious-work, but I'm hopeful it won't be much work at all (famous last words).

**Comment by timhabermaas** [comment]
Well, I don't consider removing one line of code and browsing through the parts where underscore was/is used "fun". ;)

**Comment by jfly** [comment]
Fair enough!
