### ISSUE TITLE
Add a results_posted field to the competition table?

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#359]
Apparently using Competition.results.count is not good for perfomance...

**Comment by timhabermaas** [comment]
Have you tried `EXISTS (SELECT id FROM results WHERE results.competitionId=?)`? This should be faster than a `COUNT`.

**Comment by timhabermaas** [comment]
In ActiveRecord terms: `Result.exists?(competitionId: 'foo')`

**Comment by pedrosino** [comment]
Looks good! Let's see in staging...

**Comment by pedrosino** [comment]
Doesn't look that good anymore :(

The queries still take too long with 2k competitions.

I guess it wouldn't hurt to add the column to the table.

**Comment by jonatanklosko** [comment]
Same as #570, already fixed in #572.
