### ISSUE TITLE
Remove FIXME in regulations build system

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#373]
See #351.
The SEPARATE label will be removed from regulations/translations in the next version, until then the build system has to automatically remove them.
I'll remove this when regulations are updated.

**Comment by jfly** [comment]
I believe there's also https://github.com/cubing/wca-regulations/issues/319 and https://github.com/cubing/wca-regulations-translations/issues/18 to track this.

**Comment by viroulep** [comment]
Yes, but both of them are going to be closed in the upcoming days, we probably want to keep this one one opened to remember that I have to fix this once the next version of the regulations is released.
