### ISSUE TITLE
Formatting of poll descriptions

### ISSUE THREAD

**Issue by Laura-O** [cubing/worldcubeassociation.org#378]
I have started to create some polls yesterday and I realized that the formatting of the field for additional information isn't good.
The main reason for this is that the description field is defined as h4 with 18px font-size and bold text, while the voting options are 14px and normal text. That makes the whole poll look a bit unbalanced and the voting options are not easy to recognize, please see this screenshot for an example:

![bildschirmfoto 2016-02-06 um 10 42 32](https://cloud.githubusercontent.com/assets/362249/12865992/6cafe2de-ccbe-11e5-8613-32d3575cc539.png)

I fixed this problem by defining a new heading in Markdown which obviously closes the h4 tag and the text below is written in normal fonts (like the voting options), so this is not urgent. But it would be cool if you could simply remove the h4-tag from the description field. Thank you! :-)

**Comment by pedrosino** [comment]
Thanks for the feedback, Laura.

We're in the middle of integrating some changes which are still buggy, so I'm not sure what is the "correct" procedure. Hopefully @jfl does.

**Comment by pedrosino** [comment]
Couldn't find a good fix for the buggy changes, so I went ahead and made this change
Does it look better like this:
![poll](https://cloud.githubusercontent.com/assets/1881933/12866792/6fb56220-ccc2-11e5-8059-901c6a09e029.png)
?

I just sent the pull request, too.

**Comment by Laura-O** [comment]
Yes, that looks much better. Thank you! :-)
