### ISSUE TITLE
We don't log user id when a request fails

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#383]
When tracking down #382, I noticed that we don't have a `[User Id] Request was made by user id:` log when a request fails. @timhabermaas, is it possible that that's because this line of code throws an exception: https://github.com/cubing/worldcubeassociation.org/blob/9afd301346c5cb65c64a1c5f486de29580e17a35/WcaOnRails/lib/middlewares/warden_user_logger.rb#L10, which keeps https://github.com/cubing/worldcubeassociation.org/blob/9afd301346c5cb65c64a1c5f486de29580e17a35/WcaOnRails/lib/middlewares/warden_user_logger.rb#L11 from happening? Is there any good way around this? Could we add a `begin...ensure` that tries to log the `warden_user`?

**Comment by timhabermaas** [comment]
I think catching all exceptions (and reraising them) is the way to go. I'll submit a PR.
