### ISSUE TITLE
Issues with /competitions on mobile

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#387]
They have a left border, but no right border. The field just goes on past the screen:

![screenshot 06_47pm fev 09 2016](https://cloud.githubusercontent.com/assets/1881933/12930180/e748d8ec-cf5d-11e5-98f4-276ac7a80eab.png)

**Comment by jfly** [comment]
This was introduced in Pedro's changes in #319.

I think one fix might be to put the <table> inside of a [`div.table-responsive`](http://getbootstrap.com/css/#tables-responsive), which might prevent all the horizontal space for the form.

**Comment by Luis-J-Ianez** [comment]
Following @jfly instructions, here you are a couple of screenshots.

**The screen as I land to the page**

All the screen is scrolled and what's worst, the competitions are scrolled too.

![screenshot_2016-02-09-22-41-22_com android chrome](https://cloud.githubusercontent.com/assets/2398227/12931565/c23796c6-cf7e-11e5-8057-d56056815c42.png)

**The map**

Seems not to follow the logical `<div class="row">` ... `<div class="col-xs-...>` order.

![screenshot_2016-02-09-22-42-01_com android chrome](https://cloud.githubusercontent.com/assets/2398227/12931571/ca064ed8-cf7e-11e5-943d-2694603b7d4b.png)

**Comment by pedrosino** [comment]
Made some changes to this. Can you people try again? @Luis-J-Ianez 

I didn't intentionally fix the no-right-border issue, but it seems to be gone.

Unfortunately the google map needs all parents to have a defined (fixed or %) height/width for it to take all space available. I'm not sure this would be possible without significant amount of custom css, but will investigate more.

**Comment by pedrosino** [comment]
Used a hack to set the map size. It doesn't work perfect on mobile, but it looks very good to me. It's up at https://staging.worldcubeassociation.org/competitions?utf8=%E2%9C%93&event=all&region=all&years=all&search=&display=Map

**Comment by jfly** [comment]
closing in favor of #356
