### ISSUE TITLE
Account creation improvements

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#389]
With the new system, people who *have* competed before aren't always bothering to claim their WCA IDs. Also, lots of people are signing up with just their first name.

- [x] Change "Name" to "Full name" (done in https://github.com/cubing/worldcubeassociation.org/commit/9afd301346c5cb65c64a1c5f486de29580e17a35)
- [x] Here's what the old php system said: https://github.com/cubing/worldcubeassociation.org/commit/90610994f277046b1bae8f9518fad811f34bd06b#diff-0da243fb611c118a0cc4f87dee818233L109, which must have worked better.
- [x] Require that people either have a WCA ID, have claimed a WCA ID, or check the "I am a first time competitor" checkbox.

**Comment by MatteoColombo** [comment]
I'm receiving a lot of registrations without the surname, most of them from first-timers.

Would it be possible to split "Full name" into two separate input boxes? 
I think that those who aren't English native speakers may get confused.

**Comment by jfly** [comment]
Hey @MatteoColombo. Thanks for the feedback, we don't check any of this ourselves, so it's very valuable to know how delegates and organizers are managing with the current system. The software team is pretty loathe to split the name field into 2 text boxes (it's not something I'm wholly opposed to, but it's something I want to talk to a lot of people about before we do). We actually have some pending changes, please see #413 and let us know what you think of those changes!
