### ISSUE TITLE
User.competitions_registered_for doesn't check for registration status

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#391]
This is computed automatically at https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L10

But with the new registration system, we have a status column.
I think only registrations with "a" status should be selected here (and appear at My Comps)

**Comment by jfly** [comment]
If we were to change this association to only look for accepted registrations, then it would be impossible to query for a user's pending registrations. I think that anyone who wants only a users accepted registrations should explicitly ask for them.

I'm going to close this issue, but will gladly accept a PR that changes the mycomps page to query for only accepted registrations.
