### ISSUE TITLE
Datetimepicker can't tabNext if the user clicked in whitespace to defocus

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#396]
This causes `$.tabNext();` to be called while the body of the page is focused, which scrolls me to the very top of the page. 

before:

![2016-02-21_21 30 03_662x703_kaladin](https://cloud.githubusercontent.com/assets/277474/13210275/59fffb76-d8e2-11e5-9c7b-94b9bcafc9f6.png)

after:

![2016-02-21_21 30 06_662x703_kaladin](https://cloud.githubusercontent.com/assets/277474/13210277/5e90c6ca-d8e2-11e5-8a84-9361c27cfc87.png)

@pedrosino, can you look into this?

**Comment by pedrosino** [comment]
Is this on mobile?
Do you have to click out of the picker to "finish the process"?

**Comment by jfly** [comment]
No, this is on desktop. I just clicked in and clocked out, I think.
