### ISSUE TITLE
Test phpBB email

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#40]
@gagou9, could you look at https://staging.worldcubeassociation.org/forum/ and investigate if email is working? I didn't see any configuration for email in the config.php for phpBB. See https://github.com/cubing/worldcubeassociation.org/blob/master/chef/site-cookbooks/wca/templates/forum_config.php.erb.

**Comment by gagou9** [comment]
I just did and it worked.
We'll have to test it after a reinstall before closing the issue !

**Comment by gagou9** [comment]
Works with the exim4-config done by chef.
