### ISSUE TITLE
Guests enabled checkbox looks weird alongside other checkboxes

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#404]
![2016-02-23_17 24 15_919x166_kaladin](https://cloud.githubusercontent.com/assets/277474/13272601/5270ffec-da52-11e5-8af4-c5ebf8468762.png)

I believe we can clean this up via some special `simple_form_for` configuration.

**Comment by pedrosino** [comment]
Also, "Guests enabled" is not very intuitive and I believe many delegates have no idea what it means. It could use a clearer description.
