### ISSUE TITLE
Clicking away from a date input focuses the next input, which can cause an incredibly annoying page scroll

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#409]
Say you're editing a competition's registration close datetime field like this:

![2016-02-29_20 11 09_892x703_kaladin](https://cloud.githubusercontent.com/assets/277474/13417431/b5ae61ee-df20-11e5-9624-4fcd4518ff7f.png)

Then, instead of selecting a registration close, you scroll up to the top of the page, with the intention of editing the venue details:

![2016-02-29_20 11 35_892x703_kaladin](https://cloud.githubusercontent.com/assets/277474/13417437/bb7ae9a8-df20-11e5-90d5-b3d17b44522f.png)

However, once you click on the venue details, that causes a `dp.hide` event to fire, which triggers the code @pedrosino added in #398 . This actually focuses the next field after competition registration close, which is Remarks, which causes a huge page scroll back to the bottom of the page:

![2016-02-29_20 11 19_892x703_kaladin](https://cloud.githubusercontent.com/assets/277474/13417439/c19c8828-df20-11e5-8e9e-293c2b355040.png)

@pedrosino, can you take a look at this? I plan to comment out https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/javascripts/application.js#L84-L90 until this is resolved.

**Comment by pedrosino** [comment]
As I mentioned before (but can't find where...maybe it was gchat?) dateTIMEpickers have this problem, since you have to click outside to close the pop up.

Maybe we can treat them different from regular datepickers and do nothing instead of tabbing next?
