### ISSUE TITLE
Should we remember password and password validation on account creation validation errors?

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#414]
As of #412/#413, it's more likely that we're going to get validation errors when creating accounts, which makes this more obvious/annoying. Do people know how other websites handle this?

See

![2016-03-05_10 52 22_618x818_kaladin](https://cloud.githubusercontent.com/assets/277474/13549699/62ec323a-e2c0-11e5-9799-2647ebf9c514.png)

note that pw confirmation is 4 characters long, whereas pw was only 3. After clicking sign up, here's the generated page:

![2016-03-05_10 52 30_621x813_kaladin](https://cloud.githubusercontent.com/assets/277474/13549701/75cfbaf2-e2c0-11e5-8fb2-9def62857e1a.png)

AFAIK, there's no security issue with keeping the pw and pw confirmation fields filled in. CC-ing our resident security expert @lgarron.

**Comment by timhabermaas** [comment]
_Not a security expert, but_: The password will be part of the HTML (`value="foo"`) you send back if you don't clean it, so it might end up in someone's cache.

**Comment by timhabermaas** [comment]
> Do people know how other websites handle this?

I believe I never used a website which didn't clear the password and password confirmation fields after validation failed.

**Comment by BiscuitCubed** [comment]
I agree, definitely clear pw's.

**Comment by jfly** [comment]
Sounds good to me. Closing this issue.
