### ISSUE TITLE
Registrations table header is partially transparent

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#429]
See

![image](https://cloud.githubusercontent.com/assets/277474/13993295/fe0797a8-f0dc-11e5-9aa5-0b869b5b5185.png)

**Comment by BiscuitCubed** [comment]
If you don't find what's causing the problem, you can just set the color directly. Also check to see it it somehow inherited an opacity value? I can't access one of these pages (It won't let me view my comp in April from the organizer view for some reason) so can't just play around with it.
