### ISSUE TITLE
Show number of events a registrant is registered for?

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#430]
Oliver asked for this. I guess we used to support this, but no longer do. I'm not sure where exactly we'd want to put this information... the table is already mighty full.

**Comment by pingskills** [comment]
Do we add a column at the end of the table? Or you could put it as part of the name column. For example "Jeff Plumb (3)".

Here's what the competitors page looks like for a comp in Australia:
![events](https://cloud.githubusercontent.com/assets/4403168/15349325/4e0eb7f4-1d15-11e6-8c48-86cf7109ff77.png)

**Comment by jfly** [comment]
I like that screenshot! Putting the total at the end seems reasonable to me.

**Comment by pingskills** [comment]
Great. Can you assign me this issue @jfly?
