### ISSUE TITLE
Improvements on the competitions index

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#438]
Now that it is out, let's see what can be improved:

- [x] Little flags before the competition name/link? (#58)
- [x] Fix the "Past competitions (last 90 days)" message when years=all
- [x] Have a blank line separating the years on the list
- [x] Date always on the left?

**Comment by jfly** [comment]
@pedrosino, I'm assigning this issue to you, I'm not sure if the date on left is still something that needs to be done or not.

**Comment by pedrosino** [comment]
It was requested by Ilkyoo because he used the old format to copy and paste somewhere else, but I'm working with him on an SQL query to do what he needs.

I'll update this when the situation is clearer.

**Comment by jbcm627** [comment]
Quick comment about this:
> Little flags before the competition name/link? (#58)
Why not put the flag next to the country name?

**Comment by jonatanklosko** [comment]
Hmm, I don't know, for me it looks better as it is.

**Comment by pedrosino** [comment]
Closing this.
