### ISSUE TITLE
Stricter competition name validations

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#444]
Ilkyoo wants to only allow alphanumeric characters, dash, ampersand, period, dash, colon, apostrophe, and space. That translates to the following Ruby regex: `/^[-&.:' [:alnum:]]*$/`

Unfortunately, there are 13 competitions that don't follow these rules, so in order for our model validations to still be correct, we either need to edit those 13 competitions, or have our validation be smart enough to check the date of the competition to know which rules to apply.

```ruby
irb(main):020:0> Competition.all.map(&:name).reject { |name| /^[-&.:' [:alnum:]]*$/.match(name) }
  Competition Load (48.3ms)  SELECT `Competitions`.* FROM `Competitions`
=> ["C^3 Cube Open 2014", "Clock N’ Other Stuff 2016", "Hari ng Norte (King of the North) 2015", "HOOAH! SMA 2015", "Macau Rubik´s Open 2009", "Moldavian Nationals – Winter 2016", "Poly^3 2016", "Reno/Lake Tahoe Winter 2010 Cube Competition", "(Rubik´s)^3 Baires 2.0 2011", "Campeonato de Cubos Mágicos de São Carlos/SP 2013", "SESC/Santos 2010", "SESC/Santos 2011", "Thakur Rubik’s Cube Championship 2014"]
irb(main):021:0> 
```

**Comment by jfly** [comment]
We can change all variants on apostrophe ([RIGHT SINGLE QUOTATION MARK](http://www.fileformat.info/info/unicode/char/2019/index.htm) and [ACUTE ACCENT](http://www.fileformat.info/info/unicode/char/00b4/index.htm)) to plain apostrophe.

We can change all [EN DASH](http://www.fileformat.info/info/unicode/char/2013/index.htm) to regular dash.

If we were to do the above, then we're left with the following 9 competitions:

```ruby
irb(main):037:0> Competition.all.map(&:name).reject { |name| /^[-&.:'’´—– [:alnum:]]*$/.match(name) }
  Competition Load (18.2ms)  SELECT `Competitions`.* FROM `Competitions`
=> ["C^3 Cube Open 2014", "Hari ng Norte (King of the North) 2015", "HOOAH! SMA 2015", "Poly^3 2016", "Reno/Lake Tahoe Winter 2010 Cube Competition", "(Rubik´s)^3 Baires 2.0 2011", "Campeonato de Cubos Mágicos de São Carlos/SP 2013", "SESC/Santos 2010", "SESC/Santos 2011"]
```

I suggest the following renames:

- `C^3 Cube Open 2014` -> `C Cubed Cube Open 2014`
- `Hari ng Norte (King of the North) 2015` -> `Hari ng Norte: King of the North 2015`
- `HOOAH! SMA 2015` -> `HOOAH SMA 2015`
- `Poly^3 2016` -> `Poly Cubed 2016`
- `Reno/Lake Tahoe Winter 2010 Cube Competition` -> `Reno Lake Tahoe Winter 2010 Cube Competition`
- `(Rubik´s)^3 Baires 2.0 2011` -> `(Rubik´s)^3 Baires 2.0 2011`
- `Campeonato de Cubos Mágicos de São Carlos/SP 2013` -> `Campeonato de Cubos Mágicos de São Carlos/SP 2013`
- `SESC/Santos 2010` -> `SESC Santos 2010`

**Comment by larspetrus** [comment]
For this to be usable, you need error messages that points out what characters are invalid. That may be most of the work.

**Comment by FatBoyXPC** [comment]
Is there any reason why we can't just say "This contains invalid characters, here's a list of valid characters"?

**Comment by larspetrus** [comment]
That would be lot better than nothing, but I there are near identical looking quotes and dashes.

Also, that list will be very long.

**Comment by pingskills** [comment]
Can we substitute the near identical quotes and dashes that aren't valid in the competition name for the one's that are?

**Comment by jfly** [comment]
Sure, I'm ok with sanitizing the input a bit with a replace all before enforcing our validations.

**Comment by pingskills** [comment]
Should this restriction also apply to competition nicknames (cellName). I'm assuming so.

**Comment by pingskills** [comment]
Could we get rid of cellName completely? :)

**Comment by pedrosino** [comment]
I guess we could stop using it, but not get rid of the actual column in the database...
