### ISSUE TITLE
Show city/country in results post

### ISSUE THREAD

**Issue by Meneghetti** [cubing/worldcubeassociation.org#445]
Currently the competition results are announced in the main page like this: "_Lucas Etter wins Michigan Cubing Club Alpha 2016_".
Why not "_Lucas Etter wins Michigan Cubing Club Alpha 2016 in Ann Arbor, Michigan, USA_"?

**Comment by pedrosino** [comment]
I think that's a good idea, and consistent with the competition announcement.

I'll try to take a look.

**Comment by Luis-J-Ianez** [comment]
I don't like this idea, because the competition name already includes the place name in a lot of cases, and the announcement will look redundant. Example: the sample given by Diego himself.

**Comment by pedrosino** [comment]
Well, as I said, we do this for competition announcements, and we use the name on the title. The redundancy already exists...

**Comment by Luis-J-Ianez** [comment]
In my head both cases (competition announcements and results announcements) are very different --for competition announcements knowing where will it be celebrated it's a priority, while for results it is not.

**Comment by jfly** [comment]
I agree with Pedro here: konsistency is king. It's also worth mentioning that we shouldn't agonize too much over this, as I would like for our homepage to get redone (see #53 for some ideas).
