### ISSUE TITLE
Special flags for competitions taking place in multiple countries.

### ISSUE THREAD

**Issue by jonatanklosko** [cubing/worldcubeassociation.org#447]
In #440 national flags has been added to the competitions index, but at the moment there are no flags for peculiar competitions taking place in multiple countries. [Here are the 'countries'](https://github.com/cubing/worldcubeassociation.org/blob/131bb018854e23a7f8e74131280d88996c763585/WcaOnRails/app/models/country.rb#L1808-L1833).

![image](https://cloud.githubusercontent.com/assets/17034772/14120359/b3f10c88-f5f2-11e5-8735-7bfd1a0ed02b.png)

**Comment by pedrosino** [comment]
Maybe the olympic flag: http://www.iconarchive.com/tag/olympic-flag
