### ISSUE TITLE
Search competitions for specific events

### ISSUE THREAD

**Issue by FatBoyXPC** [cubing/worldcubeassociation.org#448]
A competitor has requested a feature to be able to search for competitions containing specific events. The easiest way to accomplish this is to change the select to a multi-select. The same user, however, mentioned being able to click on the cubing event icons (event-*) to "enable" them in the seach. This certainly does feel like good UX.

Another user has also requested sorting the returned competitions in order of most matched events to fewest matched events.

**Comment by jfly** [comment]
This sounds awesome! I've created the ment2 label for projects like this that are a bit more involved. (ment1 projects are supposed to be things that would take me 30-60 minutes)

**Comment by jonatanklosko** [comment]
It really seems to be great, I will do this. One question here is: when two competitions have the same count of the selected events, which should go first?

**Comment by pedrosino** [comment]
I guess you could order by date as we already do.
Em 03/04/2016 10:08, "jonatanklosko" <notifications@github.com> escreveu:

**Comment by jonatanklosko** [comment]
As we already do, so you mean that competitions with a start date the farthest in the future goes on the top, right?

**Comment by pedrosino** [comment]
Yes, that's how I made the competitions index.
Em 03/04/2016 10:21, "jonatanklosko" <notifications@github.com> escreveu:
