### ISSUE TITLE
Flags don't fit nicely with multiday competitions

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#451]
See:

![image](https://cloud.githubusercontent.com/assets/277474/14123323/cec43f82-f5b4-11e5-990d-aee811992d7f.png)

@jonatanklosko, can you take this on?

**Comment by jfly** [comment]
Can we also update our database seeds to create some multipleday competitions and some single day competitions? If we had that, then I'm sure we would have noticed this before pushing it live.

**Comment by pedrosino** [comment]
Wasn't this fixed by #452 ?

**Comment by jfly** [comment]
Yes it was! Thanks for checking.
