### ISSUE TITLE
Competitions list current view should show *all* upcoming competitions

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#457]
Right now, it filters to competitions in the current year. @pedrosino, why is that? See relevant code [here](https://github.com/jfly/worldcubeassociation.org/blob/c94c69e084252a614f5b4834a3d37c9a83865fb5/WcaOnRails/app/controllers/competitions_controller.rb#L50-L51):

```ruby
      @competitions = @competitions.where("CAST(CONCAT(year,'-',month,'-',day) as Datetime) > ? AND year = ?",
                                          (Date.today - PAST_COMPETITIONS_DAYS), Date.today.year)
```

With the current behavior, as we get into November/December, the number of upcoming competitions will slowly diminish.

**Comment by pedrosino** [comment]
That's because I'm dumb :)

Don't know why I did that. I'll send a fix.
