### ISSUE TITLE
Hourglass Icons aren't intuitive

### ISSUE THREAD

**Issue by FatBoyXPC** [cubing/worldcubeassociation.org#470]
@jonatanklosko - this is just a minor nitpick, but when @jfly pushed the code to production I saw the hourglass icons and was wondering what they were for. He explained it to me, but maybe it would be good to put a title attribute on the i element so that when a user mouses over the icon they'll get a friendly message?

**Comment by jonatanklosko** [comment]
Good idea, thanks for pointing it out!

**Comment by jonatanklosko** [comment]
To close.

**Comment by FatBoyXPC** [comment]
Just FYI, you can type "fix/fixes/fixed" or "resolve/resolves/resolving" followed by the the issue number (#470 in this case) to auto close issues when the commits make it to the master branch (or maybe the default branch? Not sure, but in this case, master is default!)

**Comment by jonatanklosko** [comment]
I thought that I did it but now realised that I made a typo.
