### ISSUE TITLE
Search competitions for all matched events

### ISSUE THREAD

**Issue by FatBoyXPC** [cubing/worldcubeassociation.org#471]
This is definitely related to #448. The requested behavior, that was not made clear in the original issue/post was that the expected results would have all of the events in the search, rather than "all or some".

Would it be terribly difficult to have tables per count of events matched? Such as "All Events Matched:" and show those competitions, then "N events matched" after that? We could further break it down with something like "3 events matched (3x3, 2x2, BLD), but I certainly feel like that's just going too far :)

**Comment by FatBoyXPC** [comment]
Assigning @jonatanklosko because he built this masterpiece :)

**Comment by jonatanklosko** [comment]
Yes, as Jeremy indicated it would be cool to have such labels. I decided to do it in another PR :)

**Comment by jonatanklosko** [comment]
Pedro said that it's better not to show the competitions that don't match at least one of the selected events.

**Comment by pedrosino** [comment]
The way I see it is:
"select only competitions with ALL of the events marked". I'm not sure if it's intuitive if we select competitions that match one or more events.

**Comment by jonatanklosko** [comment]
Hmm, but when we mark 7 events, it's reasonable to select ones matching 6 of them. I think when we add lables with count of matched events, it would be intuitive enouth. But as you said there's no reason to show competitions with 0 matches. I would left it as it is and add the labels mentioned before. Thoughts?

**Comment by pedrosino** [comment]
Ah, I'm not sure...At least the way I would use the search would be as I described. If I marked 333bf and clock, I'm interested in competitions with both of them. But I guess what you said also makes sense.

**Comment by jfly** [comment]
I can see how the current behavior would be confusing if you really only care to find competitions that have 4bld and feet in the US (spoiler alert: there probably aren't any, but you're going to see a bunch of competitions with 4bld and get excited)

I think things will be clearer with the labels. If it's still confusing after that, let's revisit.

**Comment by FatBoyXPC** [comment]
If we're going to do labels for which events matched, can we still at least have an "All events matched" label so that way you don't have to compare the matched events label to the selected icons?

**Comment by jfly** [comment]
As per #480, we "We decided to abandon the idea with labels because it wasn't very clean.". Check out the PR for more details.

@FatBoyXPC, feel free to reopen this issue if you have a better idea for how to handle this!

**Comment by FatBoyXPC** [comment]
I do believe that the requested behavior is exactly how #480 implemented it. Reading my original post, this didn't seem clear. I think I was just trying to go with the flow here.

In case this creeps back up in the future: in the event somebody complains about the strict matching behavior, we could possibly have buttons that say "match all events" and "match one or more of the selected events". Just a thought!
