### ISSUE TITLE
About the "Waiting list" wording

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#474]
I got quite a few feedback about people getting mislead by the use of "waiting list".
At first sight one may think the registrations are full when it's just that his registration is pending approval.

I don't have a very precise suggestion; without putting too much thoughts into it I see at least two options :

- Change the wording to something like "your registration is pending approval or is on waiting list"
- Make the approval process independent of the list the competitor is in (and create the appropriate shortcut like "approve and move to competitor list"/"approve and keep on waiting list"). The message could then display "pending approval"/"waiting list" accordingly.

What do you think ?

**Comment by jfly** [comment]
Thanks for making this issue, @viroulep. What do you think of my thoughts on https://github.com/cubing/worldcubeassociation.org/issues/328#issuecomment-181988291?

I'm skimming here, but I think what you called "pending approval" is the same thing that I called "pending review"?

**Comment by viroulep** [comment]
Yes, this is the same thing :)

I like the last proposal there ! It's a bit more work for the organizer (and software team :p) but definitely makes things more clear from a competitor point of view !

I probably should have posted there, I must admit I quickly scrolled through the first page of issues and didn't actually dig for a similar issue.

**Comment by pingskills** [comment]
@jfly @viroulep has this issue been resolved now?

**Comment by jfly** [comment]
Not yet! It's something competition organizers keep asking me about, as it causes a lot of confusion for competitors.

**Comment by larspetrus** [comment]
Can we pick a less misleading phrase right now, and leave the larger redesign for later?

**Comment by jfly** [comment]
I'm closing this issue in favor of the larger redesign discussed on #328. That said, if someone wants to do as @larspetrus suggests and tweak the current phrasing, I'd be happy to accept a PR.
