### ISSUE TITLE
Competitions page sorting

### ISSUE THREAD

**Issue by FatBoyXPC** [cubing/worldcubeassociation.org#486]
I was talking to a friend while he was on /competitions. A couple things were made clear to me while he tried to use this page.

He wanted a way to scroll to "right above past competitions" to see when the next competitions he could go to would be. He was unhappy that it's not "immediately obvious" when he gets to the past competitions section. This means that he did not notice the < clock > controls on the page. I feel like this could use a little love in that regard, since it wasn't immediately obvious to use those. I realize the competitions are sorted the way they are because that's how they used to be sorted, but things are grouped fundamentally different now. I feel like upcoming competitions could be sorted ASC depending on date rather than DESC. Past should probably still be sorted by DESC order though.

Really, we could probably even go as far to removing past competitions from this page unless they've been searched by years. Possibly even have a "past competitions" search option rather than searching via years?

@jonatanklosko do you have any opinions here?

**Comment by jonatanklosko** [comment]
First of all I absolutely agree that we should change the order, It's not really user friendly to show competitions starting let's say 4 months from now on the top, when almost everyone search for next competitions he can go to. Also we should make the 'time navigation' more noticeable. By the time competitions will have been sorted ASC, it's not important whether we show the past comps.

**Comment by FatBoyXPC** [comment]
Feels like we're in complete agreement :)

**Comment by pedrosino** [comment]
Yeah, the controls are not very obvious. Jim had a nice suggestion, let me see if I can find it.

About the ordering, I'm fine with changing it, since we show just one list at a time (during the process we were working on maybe showing upcoming and past lists side-by-side).

**Comment by jonatanklosko** [comment]
Fixed by #490.
