### ISSUE TITLE
Exceptions on my competitions page

### ISSUE THREAD

**Issue by jonatanklosko** [cubing/worldcubeassociation.org#495]
I've found a situation when exceptions occur on the 'My competitions' page.
1st scenario:
- User creates competition
- sets delegate/organizer to himself
- doesn't set the date
- clicks 'Update Competition'
- goes to 'My competitions'

![image](https://cloud.githubusercontent.com/assets/17034772/14509179/4c703928-01cb-11e6-97a3-e10ffeb7d9d0.png)
We sort by date, but it's nil.

2nd scenario:
- User creates competition
- sets delegate/organizer to himself
- sets the date  but doesn't set the country
- clicks 'Update Competition'
- goes to 'My competitions'

![image](https://cloud.githubusercontent.com/assets/17034772/14509320/f9530300-01cb-11e6-9f83-caf6b0ecf426.png)
The reason is that the country wasn't selected.

Some quick fix would be adding to [this](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/competitions_controller.rb#L277), the following code:
```ruby
@competitions = @competitions.delete_if do |competition|
  competition.start_date.nil? || competition.countryId.empty?
end.uniq.sort_by(&:start_date).reverse!
```

But maybe there's a better way to fix this?

**Comment by jfly** [comment]
Good catch, @jonatanklosko! I personally would rather show people their competitions, rather than hiding them. I'm not sure what the cleanest implementation here would be. I imagine @timhabermaas would suggest using a nullable type/option =)
