### ISSUE TITLE
Competitions#index empty without JS enabled

### ISSUE THREAD

**Issue by timhabermaas** [cubing/worldcubeassociation.org#499]
<img width="1552" alt="screen shot 2016-04-15 at 10 37 44 am" src="https://cloud.githubusercontent.com/assets/96054/14556019/3d351b46-02f6-11e6-8f88-0d6d5e99953e.png">

Is this intentional? Why is the content hidden by default?

**Comment by jfly** [comment]
Good catch. I agree that we should be able to show something without javascript kicking in. @jonatanklosko, can you look into this?

**Comment by jonatanklosko** [comment]
You are right, I will fix this today.

**Comment by Laura-O** [comment]
The whole competition page seems to be broken here. When I enter "germany"in the search field, press enter and click on "Present", this is the result:

![bildschirmfoto 2016-04-15 um 13 34 41](https://cloud.githubusercontent.com/assets/362249/14560289/e2d0bcb4-030e-11e6-984d-c303eded9a82.png)

**Comment by Laura-O** [comment]
Furthermore, it would be nice if the "old" links would still be working.
With [this URL](https://www.worldcubeassociation.org/competitions?utf8=%E2%9C%93&region=Germany&years=current&search=&display=List) you could see a list of all current German competitions, it's now empty.

**Comment by timhabermaas** [comment]
Well, "Germany" is a country, not a city or venue, so not finding anything should be expected? I'm not sure how this worked with the old page, though.

**Comment by Laura-O** [comment]
Yes, I realized that afterwards (see my edit). I still find it rather unintuitive.
The dropdown menu is a good thing to scroll through the countries, but IMHO they should be included in the search as well.

**Comment by jfly** [comment]
For the record, here's what the old search did: https://github.com/jfly/worldcubeassociation.org/blob/95e694cd2fffb13720cfb649a8ffb094a1bd12a7/webroot/results/competitions.php#L69-L72:

```php
  foreach( explode( ' ', $chosenPatternMysql ) as $namePart )
    $nameCondition .= " AND (competition.cellName like '%$namePart%' OR
                             cityName             like '%$namePart%' OR
                             venue                like '%$namePart%')";
```

It did not look at country, although I am happy with modifying it to do so. @jonatanklosko is working on this right now.

Laura, the problem with your link is that we changed some URL parameters, so it's no longer working. If you want a list of all upcoming German competitions, you can find one here: https://www.worldcubeassociation.org/competitions?utf8=%E2%9C%93&region=Germany&search=&state=present&display=list. We should have done a better job of updating our redirects, but I totally forgot to ask @jonatanklosko to do so.
