### ISSUE TITLE
phpMyAdmin?

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#5]
I see a phpMyAdmin install here on `james-smith`: /home/cubing/worldcubeassociation.org/results/admin/phpMyAdmin/

but I see no such thing here: https://github.com/cubing/wca-website-php/tree/master/admin.

@jbcm627 do you know how this phpMyAdmin directory came into existence?

**Comment by jbcm627** [comment]
Ah... yeah, another undocumented thing that was setup.

Dreamhost currently provides a phpMyAdmin interface via mysql.worldcubeassociation.org, but the results team requested a newer version than Dreamhost provides, so that exists.

**Comment by jfly** [comment]
notes to self: https://github.com/priestjim/chef-phpmyadmin and https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-with-nginx-on-an-ubuntu-14-04-server
