### ISSUE TITLE
Filter competitions on name and short name

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#500]
I was testing the new awesome competitions page and found something strange.
Right now if you type "france" in the search field, the French championship doesn't appear (the full name is "French Championship 2016") even if the displayed name is "France 2016", which is a bit awkward.

I think the search field only compare the query to the full name, would it be possible to have it use the short name too ?

**Comment by jonatanklosko** [comment]
Good catch, the searching should be improved.

**Comment by jfly** [comment]
For anyone who wants to take this on, the relevant method is [Competition::contains?](https://github.com/cubing/worldcubeassociation.org/blob/95e694cd2fffb13720cfb649a8ffb094a1bd12a7/WcaOnRails/app/models/competition.rb#L322-L324).

**Comment by viroulep** [comment]
@jonatanklosko : since I'm going to rebuild the full website to check the regulations build, I think I can fix this easily now that I don't have to search the codebase for the relevant code.
So unless you already did it, I think you can leave this to me :)
