### ISSUE TITLE
Out of filesystem space problems

### ISSUE THREAD

**Issue by jbcm627** [cubing/worldcubeassociation.org#506]
Recently we ran into an issue with database exports failing due to running out of filesystem space. Thanks @timreyn for reporting the out of date exports resulting from this. Cron emails showed an error:
> Unable to perform database query.
\n(Error writing file '/tmp/MYmB8H7n' (Errcode: 28))

Which according to this SO post is an out of filesystem memory error.
https://stackoverflow.com/questions/7415710/mysql-writing-file-error-errcode-28

However, we have only used ~ 12 GB of 16 GB, which I assume means MySQL needs ~4+ GB of hard drive space for temporary files for creating the export. Or something. The significant contributions to hard drive usage were in:
 - 4.6G    /home: all the web stuff. Included in this are Rails logs (~ 1 GB) and old WCA exports (~1 GB).  These exports should have been cleaned up, but that may have failed due to scripts failing.
 - 3.5G    /usr: OS stuff; latex is 1 GB of this.
 - 2.1G    /var  ~1 GB of logs; btmp is sort of big ([beware hackers](https://askubuntu.com/questions/620458/is-it-safe-to-delete-btmp-from-log-on-ubuntu-14-04-rackapace-server)?); nginx logs are sort of big

I have taken the following actions to temporarily free up disk space. The export is now up-to-date.
 - The first backup ("rotation"?) of the rails and nginx logs were not compressed (along with other logs). I have compressed the rails and nginx ones.
 - I have removed old WCA export zip files.

We are currently using 8.2/16 GB. A few things could be done to address this going forward:

 - [ ] Do a better job cleaning up old exports ([here](https://github.com/cubing/worldcubeassociation.org/blob/master/webroot/results/admin/export_public.php#L219)).
 - [ ] Adjust logrotate to compress the most recent logs, and run more often (@gagou9?).
 - [ ] Latex is nice and all, but do we really need it just to generate regulation PDFs? (@lgarron)
 - [ ] Try to adjust the export script so it requires fewer resources.

**Comment by gagou9** [comment]
Hoy,
According to https://github.com/cubing/worldcubeassociation.org/blob/master/chef/site-cookbooks/wca/recipes/default.rb#L96-L102, we currently rotate logs if they are at least a day old, and we rotate them when they have reached 512M. We keep 5 gzipped log files.
That makes sure the nginx log folder cannot grow further than about 1.5G (it logs 2 files, access.log and error.log, files that go up to 512M, and 5 archives of ~50M each, that's 512M*2+50M*10 if i'm still able to do some basic mathematics :) )
Is that too much ?

I see the whole /var/log folder is currently about 750M, and has files file .7.gz extension, that means logrotate didn't take care of deleting the old logs. I think it was not setup at that time (Aug 19  2015).

I have deleted all file older that *.5.gz

Thanks!

**Comment by jbcm627** [comment]
Thanks Gael! What do you think about imposing stricter limits, maybe 512 -> 128, but keep 10 archives? I'm not sure what is most useful in practice.

I also wonder if we can keep "concise" logs that go further back but do not contain much detail, alongside short-term "detailed" logs.

**Comment by jfly** [comment]
As Gael mentioned at some point in the past, we never look at our nginx logs, so I'd totally be down to reduce the amount of nginx logs we hold on to.

Currently we only store about a month of Rails logs, and I'd like to keep more than that.

**Comment by gagou9** [comment]
`git grep logrotate` told me that logrotate is configured only for rails (l134) and nginx (l212), we tell logrotate to keep nginx logs for one month and rotate every week without looking for the log size...

**Comment by jfly** [comment]
Looks like we're low on space again:

```
~/worldcubeassociation.org/WcaOnRails @production> df -h /dev/xvda1
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/xvda1       16G   13G  2.8G  82% /
...
```

And usage of various directories:

```
~/worldcubeassociation.org/WcaOnRails @production> sudo du -sh /home /usr /var
5.1G    /home
3.5G    /usr
3.2G    /var
```

I then ran the following commands:

```
# gzip worldcubeassociation.org/WcaOnRails/log/production.log.1
# rm worldcubeassociation.org/webroot/results/misc/WCA_export214_20160409.tsv.zip
```

```
~ @production> df -h /dev/xvda1
Filesystem                                              Size  Used Avail Use% Mounted on
/dev/disk/by-uuid/c70a26ec-1dda-455c-acfd-792015b2bb6f   16G   12G  3.2G  79% /
~ @production> sudo du -sh /home /usr /var
4.3G	/home
3.5G	/usr
3.2G	/var
```

**Comment by jfly** [comment]
I decided to spin up a 32 GB server. I'm going to optimistically close this issue, but please reopen if we run into future troubles.
