### ISSUE TITLE
Delegates page broken on mobile

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#508]
![screenshot_2016-04-17-00-50-50](https://cloud.githubusercontent.com/assets/1881933/14590021/b196328c-04c6-11e6-8038-27f5bebb9fed.png)

Just saw this on my phone yesterday.

**Comment by jonatanklosko** [comment]
I think it's caused by [this](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/stylesheets/wca.scss#L50). Do you know what is this line for?

**Comment by jonatanklosko** [comment]
Hmm, when we get rid of this line we got:
![image](https://cloud.githubusercontent.com/assets/17034772/14590114/618f8d88-04f3-11e6-9bac-1198d6116fe9.png)

**Comment by jonatanklosko** [comment]
Actually the tables breaks the whole layout, look:
![image](https://cloud.githubusercontent.com/assets/17034772/14590153/4d0d1abe-04f4-11e6-8344-ce08f72a6525.png)
You can vertically scroll and it doesn't look well.

**Comment by jfly** [comment]
Is it possible that same styling is used for the search box at the top right? Maybe that's why the nowrap exists.
