### ISSUE TITLE
Feedback about the new results page 

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#510]
I was curious so I checked out what @timhabermaas made :)

I feel like there is going to be about the same feedback as for the competitions list : there is more padding between competitors than before, and we see about 45% less competitors than with the old results page :
![toto](https://cloud.githubusercontent.com/assets/1007485/14611878/b4b2c79a-0594-11e6-961b-71bb2e991cd1.png)

From what I could measure there is 10px between a line and the top of a name in the new version, whereas there is only 4px in the old version.
I wouldn't suggest going back to the "almost no padding" version, but I think removing some padding (3 or 4px ?) would make it more compact and easier to browse.

It would make it inconsistent with the competitions list, but I think people scroll results pages much more than the competitions list :p 

Except for this detail, this is very cool ! It's so much easier to navigate around events, and it looks much more "young" (or less "old").

**Comment by timhabermaas** [comment]
> I wouldn't suggest going back to the "almost no padding" version, but I think removing some padding (3 or 4px ?) would make it more compact and easier to browse.

A compromise between the old version and the new version sounds good to me. 👍 

3px padding looks like this:

<img width="1552" alt="screen shot 2016-04-18 at 8 15 31 pm" src="https://cloud.githubusercontent.com/assets/96054/14614654/60a64cfe-05a2-11e6-985e-9fbbd769ef61.png">

> I was curious so I checked out what @timhabermaas made :)

Just for the record: All of the credits belong to @jfly. I just improved rendering performance a bit. :)

**Comment by pedrosino** [comment]
Tried one page on mobile and it didn't look that good:
Em 18/04/2016 20:16, "Tim Habermaas" <notifications@github.com> escreveu:

**Comment by Laura-O** [comment]
I hope it's OK if I join this issue with some feedback:

1. Is there a reason why there are spaces after the opening bracket and before the closing bracket? This just looks wrong to me.

2. The results are difficult to compare as the results of the single attempts look quite messy:
<img width="807" alt="bildschirmfoto 2016-04-19 um 09 50 05" src="https://cloud.githubusercontent.com/assets/362249/14631532/2403d588-0614-11e6-857a-b761a527c767.png">
I think that looks a lot better without the *"text-align: right;"*.
<img width="800" alt="bildschirmfoto 2016-04-19 um 10 28 06" src="https://cloud.githubusercontent.com/assets/362249/14632513/72bd50d2-0619-11e6-90ce-77dacae89c70.png">

3. When there are competitors with long names, you have to scroll to the side to see the results (that's a 13" screen, 2560 x 1600):
![bildschirmfoto 2016-04-19 um 09 59 33](https://cloud.githubusercontent.com/assets/362249/14631790/6f467766-0615-11e6-8f34-a4f1a28822f6.png)
I think it would be much better to view and read without the left sidebar:
![bildschirmfoto 2016-04-19 um 10 12 14](https://cloud.githubusercontent.com/assets/362249/14632121/3c83f6c6-0617-11e6-951c-db6e067a85b6.png)
Maybe the buttons could be added to the top, similar like where they were before?

Sorry for all those comments. :-)

**Comment by jonatanklosko** [comment]
I agree with Laura in the case of 3rd point, the nav takes too much space (for registrations page too), it causes that the content is sticky to the right of the screen but main navigation does not. Anyway the nav is a part of the ayout and I'm not sure how it should look. In addition to point 2. I feel like the text-align: center; is the most clean solution.

**Comment by Laura-O** [comment]
Something else I noticed: as there are no logos for removed WCA events the names are overlapping in the menu:
![bildschirmfoto 2016-04-20 um 15 31 23](https://cloud.githubusercontent.com/assets/362249/14676314/38801dc4-070d-11e6-9914-f218b1ade9e4.png)

It would definitely be cool to have logos for them as well (see https://github.com/cubing/icons/issues/8). :-)

(I hope it's ok if I add more feedback here - if not, please tell me to add that as separate issues)

**Comment by viroulep** [comment]
Even more feedback : it would be cool to restore the possibility to click on the event name from the results index, to go directly to the relevant section of the "all" page.

**Comment by pedrosino** [comment]
@viroulep I just added #546 which hopefully fixes this last comment of yours.
I'll add the padding fix too.

**Comment by jfly** [comment]
Over the past few days, we've implemented a lot of the ideas from here. Thank you for creating this issue, but it's kind of unweildy to keep track of all the various ideas being thrown around here. Everyone who contributed, please take a look at the newest version of stuff, and feel free to open up new issues for each thing you thing could be improved upon!

**Comment by viroulep** [comment]
@pedrosino, I could only take a look at it now, it looks good thanks ! :)
