### ISSUE TITLE
Don't send emails as part of ActiveRecord callbacks 

### ISSUE THREAD

**Issue by timhabermaas** [cubing/worldcubeassociation.org#513]
I just ran this code locally: `User.all.each { |u| u.avatar = nil; u.save }` and a bunch of emails got sent. This is probably due to Devise's `after_confirmation` callback: https://github.com/cubing/worldcubeassociation.org/blob/f4dae648c32bc6870d7047674c1c5e3ac391b7ea/WcaOnRails/app/models/user.rb#L280.

**Comment by jfly** [comment]
Two questions:

1. I'm confused why that code would be causing the `after_confirmation` callback to fire. Do you have any idea why that is?
2. What should we be doing instead?

**Comment by timhabermaas** [comment]
> I'm confused why that code would be causing the after_confirmation callback to fire. Do you have any idea why that is?

Turns out I was wrong: The email being sent isn't the one from the `after_confirmation` callback, but the confirmation mail:

```
Welcome foo@bar.com!

You can confirm your account email through the link below:

Confirm my account ( http://localhost:3000/users/confirmation?confirmation_token=RmdzozDkLHA9oxzA79Fe&locale=en )

---
Devise::Mailer#confirmation_instructions: processed outbound mail in 455.1ms
```

This mail is only being sent for a few users and I've no idea why it's being sent. Time to dive into Devise internals I guess.

> What should we be doing instead?

Sending the mail in the controller. But that probably requires overwriting some Devise controllers (one of the reason why I don't like it - the customized devise often ends up more complicated than writing it from scratch...).

**Comment by jfly** [comment]
I believe Devise has skip_* methods for stuff like this. We're using them in our seeds to avoid sending emails when seeding the database.

**Comment by jfly** [comment]
I'm going to close issue. @timhabermaas, feel free to reopen if there's something more you think we should do here.
