### ISSUE TITLE
[Enhancement] Logo redesign?

### ISSUE THREAD

**Issue by seanfrasure** [cubing/worldcubeassociation.org#516]
Kinda thought it could use a new look. Here's a prototype:
![wca logo protype](https://cloud.githubusercontent.com/assets/9723817/14660821/97790742-0676-11e6-8f1c-9d4c572c68f1.png)

**Comment by jfly** [comment]
Thanks for contributing! I don't have strong opinions about design stuff. If you are interested in pushing on this, I'd probably suggest talking to the WCA Board about this. Feel free to reach out to them directly, or you can contact the software team (software@worldcubeassociation.org), and I can put you in touch with the Board.

**Comment by seanfrasure** [comment]
I emailed them! Thanks!

**Comment by jfly** [comment]
Got it, thanks! We've started a discussion with the board about this.

**Comment by Yolomaster102** [comment]
This sucks

**Comment by seanfrasure** [comment]
![wca logo proto](https://cloud.githubusercontent.com/assets/9723817/15213053/baa117d4-1812-11e6-9416-bf7b55542e90.png)
