### ISSUE TITLE
Competitions only show first date of competition

### ISSUE THREAD

**Issue by Mollerz** [cubing/worldcubeassociation.org#518]
http://puu.sh/opswV/5ee4918856.png

Here's an example of Euros, which is definitely a 3-day competition. But we've had people come up to us about Irish Championships and how it's a one day competition, when it isn't.

I presume this is an oversight or a simple bug, let's hope.

**Comment by jonatanklosko** [comment]
Thanks for this report, it's definitely a small bug. I will fix it ASAP.
