### ISSUE TITLE
Team members page improvements

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#527]
Feedback from @SAuroux:

- [ ] Adding a new (empty) member and hitting save causes a 500
- [ ] It should be possible to leave start dates blank for members with unknown start dates.

**Comment by pedrosino** [comment]
First one is easy, I'm working on it.

About the second one, should we make a migration and allow start_date to be null?
Or set a dummy value?

**Comment by pedrosino** [comment]
Affected code:
https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/team.rb#L12-L13

https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/team_member.rb#L13-L18

Thinking about it, do we want empty start_date and valid end_date? I guess we do, for old members who we don't know when joined...but that looks kinda ugly :P I'd prefer an approximation (like jan 1st of some year).

**Comment by jfly** [comment]
I'm torn. Can you reach out to @SAuroux directly and see who we're missing exact start dates for? I imagine Ron has everything in his email, it's just going to take some digging.

**Comment by SAuroux** [comment]
Well, maybe that's a non-issue, since I plan to eventually put in a date as accurate as possible anyways. It just feels counter-intuitive to put in bogus dates instead of no date until you retrieve the missing information. I will just leave this up to you.

**Comment by SAuroux** [comment]
One more issue:

I cannot add Tyson as a former team member, since he only has a dummy account. but the type of dummy account, which is also used to list delegates of older competitions, which I should be able to select there.
