### ISSUE TITLE
Little avatar bug?

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#530]
The arrow below my avatar is gone:
![avatar](https://cloud.githubusercontent.com/assets/1881933/14768038/7be216ec-0a0c-11e6-97f4-bd9cd586a230.png)

It looks fine on local server, though.

**Comment by pedrosino** [comment]
Here's how it looks locally:
![2016-04-24-112904_136x111_scrot](https://cloud.githubusercontent.com/assets/1881933/14768146/e660068e-0a0f-11e6-83f2-9f4a21c067a8.png)

**Comment by jfly** [comment]
Duplicate of #525.
