### ISSUE TITLE
User search api is not correct about what it considers to be a "dummy account"

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#544]
See https://github.com/cubing/worldcubeassociation.org/issues/527#issuecomment-214459983

**Comment by jfly** [comment]
@SAuroux, FYI this fix has been pushed live. I see that Tyson Mao is now selectable via our team member autosearch.

**Comment by SAuroux** [comment]
Thanks Jeremy, I added Tyson now.

2016-04-28 8:23 GMT+02:00 Jeremy Fleischman <notifications@github.com>:
