### ISSUE TITLE
Podiums page is screwy for some competitions

### ISSUE THREAD

**Issue by KitClement** [cubing/worldcubeassociation.org#553]
This is the only such case I've seen, but this competition has some ordered 3-1-2, and others 3-2-1:

https://www.worldcubeassociation.org/competitions/FantabulousMichigan2015/results/podiums

Full results page is working fine though.

**Comment by jfly** [comment]
For posterity after we fix this, here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/277474/14931643/dc530bbc-0e21-11e6-8cfc-65e93d2c57e1.png)

**Comment by jfly** [comment]
Thanks for the report, @KitClement!

**Comment by jfly** [comment]
Woahhh, somehow https://www.worldcubeassociation.org/competitions/FantabulousMichigan2015/results/podiums is working even without touching the filesystem. We're going to have to look into this and understand how it worked sometime =)
