### ISSUE TITLE
Rankings ties are marked in gray - except for the first

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#557]
![ties](https://cloud.githubusercontent.com/assets/1881933/14937094/1e6e2818-0ed3-11e6-9524-14575844fc9b.png)

I can't remember how it looked before, but I think they all should have the same color. It's not like Ben is more deserving of the 8th place than the rest :P

**Comment by jfly** [comment]
This was intentional, but I'm not that attached to it. I'm going to go ahead and close this, but feel free send in a PR changing this and we can have a discussion over there.
