### ISSUE TITLE
Clear fields under nav tabs on sign up page when switching tabs

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#567]
Right now, you could fill out some stuff under the "I have never competed" tab, then switch to the "I have competed" field, click submit, and all those fields from the "I have never competed" tab would still get submitted.

I think the easiest fix to this would be to add a little javascript that clears the fields whenever the nav is changed (we wouldn't want to do this on page load, though, for fear of removing validation errors).

**Comment by jfly** [comment]
This should be done before #566.

**Comment by timhabermaas** [comment]
Another idea: Make two "Sign up" buttons and move them into the tabs. When giving the buttons different names you can keep them apart in the controller: `f.submit name: :has_competed` -> `params[:has_competed].present?` So you'd know which tab the user submitted. This way you can also show the correct tab after validation fails.

**Comment by jfly** [comment]
Ah, leaving the button outside was actually intentional, in order to give people something to click, rather than freaking out about no button being visible originally.

We actually *do* render the correct tab visible when there are validation errors. See test here: https://github.com/cubing/worldcubeassociation.org/blob/50cf4371dffee5adc38b5927423d0db377342d8e/WcaOnRails/spec/features/sign_up_spec.rb#L76-L81, and application code here: https://github.com/cubing/worldcubeassociation.org/blob/50cf4371dffee5adc38b5927423d0db377342d8e/WcaOnRails/app/views/devise/registrations/new.html.erb#L75-L89.

You're right though, there's no need for more javascript here... our backend code should be smart enough to do the correct thing by looking at the `claiming_wca_id` hidden input.

**Comment by timhabermaas** [comment]
Okay, I didn't know the tabs aren't visible initially.
