### ISSUE TITLE
Delete regulations/style-guide.md

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#577]
This is now at https://github.com/cubing/wca-regulations/blob/draft/style-guide.md

I'd make a PR directly, but I can't figure out how to do that on the GitHub interface. Filing this so we don't forget.

**Comment by jfly** [comment]
Assigning to @viroulep as per @jonatanklosko's comment [here](https://github.com/cubing/worldcubeassociation.org/pull/747#issuecomment-229217530).

**Comment by viroulep** [comment]
Fixed in #747.
