### ISSUE TITLE
Change controller's actions to not rely on localized value

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#584]
To avoid issues with internationalization, controllers should not rely on a localized value to do some actions.
Right now there is at least [one controller](https://github.com/cubing/worldcubeassociation.org/blob/66a9530b6ab0e6dd23839a3f552862901363243c/WcaOnRails/app/controllers/competitions_controller.rb#L286) which does that, I'll try to find and change them all.
See this [discussion](https://github.com/cubing/worldcubeassociation.org/pull/460/#discussion_r58292632) for some more details.

**Comment by viroulep** [comment]
So after looking for any use of something like `params[:*] ==` or `case params[.*]` I found only four matching controllers: the [registrations](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/registrations_controller.rb#L98), [polls](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/polls_controller.rb#L45), [competitions](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/competitions_controller.rb#L279), and [admin](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/admin_controller.rb#L41).

Even if some values look like labels, the only things that needs to be adapted are the `region`/`year`/`state` selectors in the competitions' index. The other buttons actually have a label separated from the value :)

**Comment by jfly** [comment]
@viroulep, could you update the links in https://github.com/cubing/worldcubeassociation.org/issues/584#issuecomment-239627491 to point at the correct lines? I personally always is press "y" before copying a link (see https://help.github.com/articles/getting-permanent-links-to-files/).

**Comment by viroulep** [comment]
Done!
Thanks for the 'y' trick :)

**Comment by viroulep** [comment]
I think I "fixed" this in #874, the `region`/`year`/`state` selectors actually also had a label separated from value, and I managed to translate these without touching the the current action code.
