### ISSUE TITLE
Check for missing translations

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#588]
In addition to the rails "missing translation" error, we probably want a tool to check and tell us which keys are used and missing in a translation.

**Comment by larspetrus** [comment]
Back when I did Rails i18n in 2013, there was no such tool. But it's easy to make a test that scans the project code for used keys, and compares that set to the the keys in the language files. This would also address #587.

The only catch is that you need to make the calls in a consistent, scannable format. Which is easy.

Some people are uncomfortable with tests that test other things than functionality, but it's a powerful and useful technique.

**Comment by viroulep** [comment]
I think it's fine to have these kind of tests, and there is already rubocop that does some non functional tests.

Indeed; in that case I guess all the calls for translations should be fully scoped, ie use:
```ruby
t 'full.context.mykey'
```

instead of:
```ruby
t '.mykey'
```
right ?

I'm also wondering if this [kind of changes](https://github.com/cubing/worldcubeassociation.org/pull/594/files#diff-2718f441e5be691a3eb69f5d2618392fR3) would break the implicit scope for a key used inside this block, by adding an extra `results_nav` level before the `nav` one. In that case using full scope would prevent any issue.

I also have no idea if it would be simple to detect simple_form's default hints that miss a key: sometimes we use an explicit hint, sometimes it gets the hint from [here](https://github.com/cubing/worldcubeassociation.org/pull/460/files#diff-3b35e11b9e261cae013c8cd8c46ecae1R108) for instance (maybe sometimes we don't have hint at all ?).
Maybe we could always specifies explicit hints, that's a bit more work in the erb, but it would ease checking the keys.

**Comment by jfly** [comment]
As a first order approximation, I'd be ok with assuming that our English translations are complete, and then looking for missing translations in all our other languages. I think that's what https://github.com/svenfuchs/rails-i18n#test-your-locale-file does?

**Comment by jonatanklosko** [comment]
I've just search for something appropriate and the first thing I stumbled upon was [this](https://github.com/glebm/i18n-tasks/blob/master/README.md). It seems to fit our needs perfectly.

**Comment by viroulep** [comment]
Done in #781
