### ISSUE TITLE
Assign delegates and organizers for all old competitions

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#59]
Right now we copy user email's into competition announcements. Unfortunately, our schema is frozen until we move everything over to rails.

**Comment by jfly** [comment]
Places where we refer to the unstructured `wcaDelegate` field:

```bash
~/gitting/worldcubeassociation.org/webroot/results @kaladin> git grep wcaDelegate
admin/_helpers.php:      wcaDelegate
admin/competitions_manage.php:    SELECT id, date_format(year*10000+month*100+day,'%e %b %Y') date, name, cityName, countryId, wcaDelegate, organiser, venue, cellName
admin/competitions_manage.php:      unTag( $where ) . '<br />' . unTag( $wcaDelegate ) . '<br />' . unTag( $organiser )
admin/export_public.php:                              wcaDelegate, organiser, venue, venueAddress,
admin/show_competition_details.php:    UNION ALL SELECT id, year, 'wcaDelegate' keey, wcaDelegate value FROM Competitions
admin/upload_results.php:$competitions_query = "SELECT id, name, countryId, wcaDelegate
admin/upload_results.php:          . strip_tags(processLinks($competition->wcaDelegate));
includes/_choices.php:  $competitions_query = "SELECT id, name, countryId, wcaDelegate
includes/_choices.php:            . strip_tags(processLinks($competition->wcaDelegate))
includes/competition_edit_Model.php:      'wcaDelegate',
includes/competition_edit_Model.php:                   wcaDelegate='$wcaDelegate',
includes/competition_infos.php:  showItem( 'key', "WCA Delegate", array( $wcaDelegate ));
~/gitting/worldcubeassociation.org/webroot/results @kaladin> 
```

**Comment by jbcm627** [comment]
It is no problem to add a new table, right? Would two tables, competitionId => delegateWcaId and competitionId => organizerWcaId help rails handle this? (Or rather than wca id, email or rails user id or something.)

I think this job will involve a lot of manual editing due to the wcaDelegate and Organizer fields being so inconsistent, so it wouldn't necessarily be a good candidate for a rails script - I could take this on if you think it is a good idea.

**Comment by jfly** [comment]
I think that's a great plan, Jim. It has a nice benefit of degrading nicely for old competitions.

Help migrating the database would be very appreciated =)

**Comment by jfly** [comment]
Pedro is working on this.

**Comment by pedrosino** [comment]
Ok, I think I'm done.

All competitions except for FMCEurop2015 have delegate(s) assigned.
I created an account for those who didn't have one.

**Comment by pedrosino** [comment]
FMC Europe is now done.
I created another account for Tyson Mao, but already had one, so I ran this:

update competition_delegates set delegate_id = '5' where delegate_id = '1661';
delete from users where id = '1661';

**Comment by jfly** [comment]
I've run a migration to remove the `wcaDelegate` and `organiser` fields from the `Competitions` table. I'm currently running a database dump and backup so we don't lose any of Pedro's awesome work =).
