### ISSUE TITLE
Negative days inside nearby competitions table

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#598]
Before we would show something like '25 days before'.
But now it appears as '-25 days before'

![minus](https://cloud.githubusercontent.com/assets/1881933/15118782/0eda6f02-15e4-11e6-9c9b-12b3582ff074.png)

I think this is the cause: https://github.com/cubing/worldcubeassociation.org/pull/460/files#diff-4d4455b17c013ab9ef2fff749e71b0c4R15

Unfortunately I'm clueless about what Philippe has done, so I don't think I can fix it :(

**Comment by jfly** [comment]
Thanks for reporting, Pedro. Philippe's changes are quite simple: he just pulled out a lot of our strings. If you don't understand this, please reach out to me sometime and we can talk about it.
