### ISSUE TITLE
Enforce "extra validations" for competitions that are visible and not confirmed

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#604]
See https://github.com/cubing/worldcubeassociation.org/pull/597/files#r62686950.

Right now, we have some extra Competition validations that kick in when confirming a competition. However, it is possible for a board member to make a competition visible without ever confirming it. We should enforce the extra validations when the competition is being confirmed *or* when the competition is being made publicly visible.

**Comment by pingskills** [comment]
Adding the validation is easy but it causes some issues with our tests. A lot of tests create a competition and the default is `showAtAll true` which suddenly causes the new validation to run and hence the FactoryGirl create fails! I then thought I'd set `showAtAll false` in the competition factory which works fine for the competition tests but then a lot of other tests create a competition expecting it to be visible! I can go through and update those tests to set `showAtAll true` but then I also need to add `:with_delegate`?

Or maybe the default creation of a comp should be `showAtAll true` and `:with_delegate`? Then I can modify any tests that fail to modify these new default values?
