### ISSUE TITLE
Serialize events fields

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#63]
Competitions.eventSpecs and Preregs.eventIds should be serialize for better handling, instead of using regular expressions to read.

We're going to leave the db schema frozen until cubing/wca-website-php is dead, but this is a good candidate for cleanup after that.

**Comment by jonatanklosko** [comment]
I've already moved Preregs.eventIds to their own table and doing the same for Competitions.eventSpecs is covered by #95, so I'm closing this.
