### ISSUE TITLE
DNF results in Podiums/Winners

### ISSUE THREAD

**Issue by KitClement** [cubing/worldcubeassociation.org#634]
On the old results pages, the logic was changed to not show on the winners/podiums page any competitor who DNFed an attempt.  This seems to have changed back to the old method of just showing those DNF competitors, as seen here:

https://www.worldcubeassociation.org/competitions/PDXCubingBeta2015/results/podiums

And here:

https://www.worldcubeassociation.org/competitions/PDXCubingBeta2015

**Comment by jfly** [comment]
@KitClement is referring to this fix: https://github.com/cubing/worldcubeassociation.org/commit/f3770d5aea958b1843818921bea1d206957a98b1

**Comment by jonatanklosko** [comment]
Pushed live =)
