### ISSUE TITLE
Displaying blank DOB in change_person.php

### ISSUE THREAD

**Issue by SAuroux** [cubing/worldcubeassociation.org#638]
Currently, blank DOBs are shown as 1/1/2016, which is very confusing. It would be very nice to just display blanks in the dropdown for blank DOBs. Additionally, there are cases were the results team even needs to change a DOB to blank (e.g. when a delegate entered some bogus date instead and cannot retrieve the correct DOB of a competitor).

**Comment by jonatanklosko** [comment]
@SAuroux I'm porting this page to Rails and will finish soon. It will be very handy =)

**Comment by SAuroux** [comment]
Ok, that sounds awesome, thank you. :)

**Comment by jonatanklosko** [comment]
Closes via #645.
