### ISSUE TITLE
Datepicker styling bug?

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#646]
I was just adding @pingskills to the software team, and ran into this ugliness:

![image](https://cloud.githubusercontent.com/assets/277474/15419913/4e717164-1e1e-11e6-97ed-f8b79f7bd44f.png)

The problem appears to be due to the fact that we have a table inside of a table here:

![image](https://cloud.githubusercontent.com/assets/277474/15419956/95eecfbe-1e1e-11e6-9d5c-7521d9d2808f.png)

Maybe it's possible to get the bootstrap popup to attach itself to the `<body>`, rather than deep in the DOM as it is doing right now?

**Comment by jonatanklosko** [comment]
[This](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/stylesheets/wca.scss#L100) should be changed to `& > tbody ...`
