### ISSUE TITLE
Get rid of the user && user.can_FOO? pattern

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#662]
In a lot of places, we want to check if a user can do something, but we don't want to blow up if the current user is not logged in. There's a common pattern emerging for doing this, and it's all over the place. See:

```
~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> git grep "\(.*\) && \1.can"
app/controllers/users_controller.rb:    unless current_user && current_user.can_edit_users?
app/models/competition.rb:    self.showAtAll || (user && user.can_manage_competition?(self))
app/models/competition.rb:    results_posted? || (user && user.can_admin_results? && !results.empty?)
app/models/registration.rb:    if user && user.cannot_register_for_competition_reasons.length > 0
app/views/competitions/_nav.html.erb:      if current_user && current_user.can_manage_competition?(@competition)
app/views/competitions/_nav.html.erb:      if current_user && current_user.can_view_delegate_reports?
app/views/layouts/_navigation.html.erb:            <% if current_user && current_user.can_create_competitions? %>
app/views/static_pages/_delegate_row.html.erb:    <% if current_user && current_user.can_edit_users? %>
```

One thought: Create a class Can and move all our `can_*` methods into it. For example:

```ruby
class Can
  def self.can_edit_competition_report?(user, competition)
    user && (can_admin_results? || competition.delegates.include?(self)) && !competition.delegate_report.posted?
  end
end
```

This way we consolidate the "we don't let you do this if you're not logged in" logic.

**Comment by larspetrus** [comment]
I think the Real Solution is Ruby 2.3 and the "safe navigation" operator.

Your examples converts to this:

    self.showAtAll || user&.can_manage_competition?(self)
    results_posted? || (user&.can_admin_results? && !results.empty?)
    if user&.cannot_register_for_competition_reasons.length > 0
    if current_user&.can_manage_competition?(@competition)
    if current_user&.can_view_delegate_reports?
    <% if current_user&.can_create_competitions? %>
    <% if current_user&.can_edit_users? %>

**Comment by jfly** [comment]
This makes me nervous: what if there's a typo in the method name we're calling safely? I'd really like to get an error rather than a false.

**Comment by larspetrus** [comment]
I think it works almost exactly like the current code, and does what you'd want. Example, to make sure we're talking about the same thing:

`if current_user&.xan_edit_users?`

If `current_user` is `nil`, this evaluates to `if nil`.

If `current_user` is an object, `.xan_edit_users?` will be called on it, and you get the same `undefined method` exception as before.

The only different behavior I can think of is if `current_user` is false, but that doesn't seem worth worrying about.
- - -
That said, I see now that one of my examples wouldn't work

`if user&.cannot_register_for_competition_reasons.length > 0`

But those are rare. And this particular one can be rephrased as

`if user&.cannot_register_for_competition_reasons.present?`
