### ISSUE TITLE
Figure out how to handle orphaned persons

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#67]
"Re-enable this:
https://github.com/cubing/wca-website-php/commit/56506f797dd3b5049423dcb66326f3a87cc57930?w=1#diff-b26b0d08a2e9c0905c72acbf6df30030R24
But in a better way. We still want to allow person data fixes and updates."

(Copied from https://github.com/cubing/wca-website-php/issues/48)

@jbcm627, could you elaborate on this a bit?

**Comment by jbcm627** [comment]
I was hoping the database could become further normalized. One of the easier changes would have involved relating rows in the Persons table to a new table containing Delegate information (or Organizer information, etc). In this case, entries would exist in the Persons table that would have no corresponding entries in Results.

There was a check that would prevent this:
https://github.com/cubing/wca-website-php/blob/56506f797dd3b5049423dcb66326f3a87cc57930/admin/persons_check_finished.php#L190
So the check is still useful in identifying incorrect data, but isn't necessarily a check that should be enforced.

**Comment by pingskills** [comment]
@jfly @jbcm627 is this issue still a problem or can it be closed?

**Comment by jfly** [comment]
I think this can be closed. Someday we can evaluate if we want to combine the users table and the persons table.

**Comment by jbcm627** [comment]
Might want to check with the results team before completely forgetting this one, as it relates to integrity of results. Do they care about entries in the Persons table without results?
