### ISSUE TITLE
Missing persons.php file

### ISSUE THREAD

**Issue by MatteoColombo** [cubing/worldcubeassociation.org#683]
The persons.php file is missing and the page gives error 404: https://www.worldcubeassociation.org/results/persons.php

The page should be accessible from the main menu: Results > Persons

**Comment by MatteoColombo** [comment]
I noticed that this works when I try to access the persons page from the homepage, but it gives 404 when I try from another (e.g. from my WCA profile).

**Comment by jonatanklosko** [comment]
@jfly have have you re-run the chef? If so maybe the redirection I've set up is wrong.

**Comment by jfly** [comment]
I just ran:

```~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> time ssh -A wca 'sudo wget https://raw.githubusercontent.com/cubing/worldcubeassociation.org/master/scripts/wca-bootstrap.sh -O /tmp/wca-bootstrap.sh && sudo -E bash /tmp/wca-bootstrap.sh production'```

Before:

```
~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> curl -I https://www.worldcubeassociation.org/results/persons.php
HTTP/1.1 404 Not Found
Server: nginx/1.8.0
Date: Mon, 30 May 2016 18:29:17 GMT
Content-Type: text/html
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/5.5.9-1ubuntu4.16
```

After:

```
~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> curl -I https://www.worldcubeassociation.org/results/persons.php
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.8.0
Date: Mon, 30 May 2016 18:29:38 GMT
Content-Type: text/html
Content-Length: 160
Location: https://www.worldcubeassociation.org/persons?
Connection: keep-alive
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
```

**Comment by jfly** [comment]
@jonatanklosko, I thought that you would run chef =). Feel free to do so in the future.
