### ISSUE TITLE
Using JS to search has broken IRC bot

### ISSUE THREAD

**Issue by jgouly** [cubing/worldcubeassociation.org#686]
Hi,

We have an IRC bot that you can use to search for a users profile (and competitions, WRs etc). It used to be done by scraping the persons.php page, now that it uses JavaScript it doesn't work.

Is there an API that we can use?

I see persons should respond to JSON (https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/persons_controller.rb#L17)

but I get an error when trying it:
https://www.worldcubeassociation.org/persons.json?region=all&search=gouly
{
  "status": "406",
  "error": "Not Acceptable"
}

How do I actually use it?

**Comment by jfly** [comment]
So, none of our API is documented right now, but the stuff we mean for others to use can be found [here](https://github.com/cubing/worldcubeassociation.org/blob/ae3f16582c3cd7c8ddccbae751461ea5a9e9778e/WcaOnRails/config/routes.rb#L103-L119). For example https://www.worldcubeassociation.org/api/v0/search?q=joey or https://www.worldcubeassociation.org/api/v0/search/users?q=duss.

**Comment by jfly** [comment]
Whoops, prematurely hit enter there. I'm going to optimistically close this issue, but feel free to reopen it to continue the conversation.

**Comment by jgouly** [comment]
Thanks, looks like the search doesn't work right.
Try searching for 'd cohen'. Only David cohen shows, where is Dan cohen! Is there a similar issue already open or shall I create one?

**Comment by jfly** [comment]
This is news to me. Please create a new issue for it!
