### ISSUE TITLE
Searching for 'D Cohen' does not list 'Dan Cohen'

### ISSUE THREAD

**Issue by jgouly** [cubing/worldcubeassociation.org#690]
Come on now, Dan still exists!

https://www.worldcubeassociation.org/persons?region=all&search=d+cohen

This doesn't show Dan Cohen, where I would expect it to. It's just showing 'David Cohen' because 'Davi**d Cohen**.

I would expect the search to be a bit more wildcardy.

**Comment by jfly** [comment]
Ah, indeed this is a regression. See the old PHP code here: https://github.com/cubing/worldcubeassociation.org/blob/1b3208477fcf44c8c81a05a06bbccfd95b1bd2dc/webroot/results/persons.php#L65-L78, which would split the query around spaces and do multiple `AND name LIKE ...` queries.

@jonatanklosko, this is a regression, so it would be nice if we fix this quickly. Can you work on this?

**Comment by jfly** [comment]
Also, it would be nice if whatever fix gets implemented here is done in a way such that the uber search for persons benefits as well.

**Comment by jgouly** [comment]
Thanks!
