### ISSUE TITLE
Bug in persons_finish_unfinished when the person's name is fixed

### ISSUE THREAD

**Issue by Luis-J-Ianez** [cubing/worldcubeassociation.org#695]
I have detected an awful bug in this script and Sébastien managed to figure out the buggy process, that later I could verify.  Reproducing it is quite simple: when you're in this step posting results, and you edit the newcomer's name to fix anything (for example, adding a period after an abbreviation) the system is unable to link the person later when you import persons.  This results in import persons NOT updating `Persons` with the provided gender and DOB, and leaving these fields blank.

Elaborating:  after persons_finish_unfinished, if a name has been fixed, `InboxPersons` contains the original version of the name (as provided in the JSON file), but `Persons` has the fixed version.  Import persons can't link `InboxPersons` with `Persons` and gender and DOB are not updated.

**Comment by jbcm627** [comment]
By 'fixed', you mean edited here?
https://www.worldcubeassociation.org/admin/edit_person
Is a simple solution to this to just have that script 'fix' things in InboxPersons?

**Comment by Luis-J-Ianez** [comment]
No, persons_finish_unfinished includes an editable input box for every newcomer, for if you want to edit (fix) their names before creating a new row in `Persons`.

**Comment by jbcm627** [comment]
Ah, I see. So at this point:
https://github.com/cubing/worldcubeassociation.org/blob/master/webroot/results/admin/persons_finish_unfinished_ACTION.php#L59
the entry in InboxPersons needs to be updated as well?

**Comment by Luis-J-Ianez** [comment]
Yes, I guess this should be enough in order for "import persons" to work well later.  (I haven't had a look into the code.)

**Comment by jfly** [comment]
I've disabled the name `<input>` for now. I won't be able to add this feature back, but @Luis-J-Ianez or anyone else watching, feel free to send in a PHP change PR that fixes this problem.
