### ISSUE TITLE
Include phpBB

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#7]
This is @gagou9's area of expertise. To have a truly one step deploy, we will need to include phpBB or replace it. I'm not familliar with how phpBB upgrades work.

@lgarron talked about potentially dropping the forum entirely, which would certainly make everyone's jobs easier =)

**Comment by gagou9** [comment]
Here is the thread about getting rid of the forum : https://github.com/cubing/wca-website/issues/12

**Comment by jfly** [comment]
Note to self: It may be possible to run phpBB without apache: http://nginxlibrary.com/phpbb-configuration/
