### ISSUE TITLE
Investigate races when creating competitions with the same id

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#70]
This was brought up by Ron here: https://groups.google.com/d/msg/wca-software/O5qFbHY9KAI/MTx8MZf-zTEJ.

**Comment by fw42** [comment]
Add a uniqueness index to the column?

**Comment by jfly** [comment]
It looks like we actually do have a unique constraint on the `id` column:

```
mysql> SHOW INDEX FROM Competitions;
+--------------+------------+----------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table        | Non_unique | Key_name       | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------------+------------+----------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Competitions |          0 | PRIMARY        |            1 | id          | A         |        2391 |     NULL | NULL   |      | BTREE      |         |               |
| Competitions |          1 | year_month_day |            1 | year        | A         |          15 |     NULL | NULL   |      | BTREE      |         |               |
| Competitions |          1 | year_month_day |            2 | month       | A         |         140 |     NULL | NULL   |      | BTREE      |         |               |
| Competitions |          1 | year_month_day |            3 | day         | A         |         797 |     NULL | NULL   |      | BTREE      |         |               |
+--------------+------------+----------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
4 rows in set (0.00 sec)

mysql> 
```

(if it's not non_unique, then it's unique, right?)

Perhaps the script that creates new competitions doesn't barf if you reuse a competition id, and instead just happily clobbers the existing row?

**Comment by jbcm627** [comment]
So this does fail with an "ID already exists" message (that is sort of hidden).

I suppose the bigger problem would be two people trying to create the same competition, but creating different IDs, and not knowing the other was working simultaneously. But I'm not sure how to avoid that one.

**Comment by jfly** [comment]
As of https://github.com/cubing/worldcubeassociation.org/commit/d9654218eec2589757bfba45d3265847fe99cc35, admins now get a "The form contains 1 error:
Id has already been taken" error when trying to create a competition with an id that is already taken.
