### ISSUE TITLE
Edit competitor country

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#71]
(copied from https://github.com/cubing/wca-website/issues/14)

I'm sure the results team know what's involved in changing a competitor's country.

**Comment by jbcm627** [comment]
Flushing this out, the use case was changing a competitor's country:

> First I did this:
> 
> UPDATE `Results` SET countryId="Morocco" WHERE personId="2015CHOK01";
> UPDATE `Persons` SET countryId="Morocco" WHERE id="2015CHOK01"
> 
> then I fixed the records using the check_regional_record_markers script.

The change_persons script might be the best place to do this, but it should issue a warning to run the check_regional_record_markers script after this change. Specifying a subId is another subtlety. I'm not sure if there are any other subtleties.

**Comment by jfly** [comment]
I did this in 54265be98553ae112ce9a3f2b74b930862287fe7.
