### ISSUE TITLE
Large images when using markdown

### ISSUE THREAD

**Issue by jonatanklosko** [cubing/worldcubeassociation.org#712]
After the user inserts an image using the awesome markdown editor, we just display it. The problem emerges when the image resolution is huge because then it could be wider than the whole page.
(Example: delegate report page)

An easy solution is to set maximal width and height via CSS, but this requires the browser to resize the image which leads to really slow image rendering.

So far the solution above would be better than nothing, but I'd like to see your thoughts.

**Comment by larspetrus** [comment]
Ideally, this should be up to the user. For that to work, they need to be able to see the resulting page. Maybe that's already how this works (I don't use the app...).

I guess `max-width` works, but when you let your users design web pages, I think you have to accept the design quality will vary a lot.

I don't think the resizing itself takes many milliseconds for the browser. Downloading a large file might, but that's fairly different.
