### ISSUE TITLE
Searching for users is not in alphabetical order?

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#723]
![users](https://cloud.githubusercontent.com/assets/1881933/16089023/cbd8eb14-32ff-11e6-89b1-ec12bde17573.png)

@jonatanklosko

**Comment by jonatanklosko** [comment]
```ruby
irb(main):002:0> User.where("name LIKE '%pala%' OR wca_id LIKE '%pala%' OR email LIKE '%pala%'").order(:name).limit(10).pluck :name
   (35.7ms)  SELECT  `users`.`name` FROM `users` WHERE (name LIKE '%pala%' OR wca_id LIKE '%pala%' OR email LIKE '%pala%')  ORDER BY `users`.`name` ASC LIMIT 10
=> [" Shriharran Radhakrishnan", "Alejo Rodriguez", "András Pál", "André Vladimir Rojas Palacios", "Ángel Daniel Palacios Xacalco", "Billy Palaiologos", "Francess Cabezas Palacios", "Jesus Sandoval", "Juan Cruz Palau", "Leroy Orven G. Palatulon"]
```

As you can see the name starts with a white character so that's not weird that it appears first. There should be stronger validation I think. So far there a couple of such names:
```ruby
irb(main):010:0> User.where("name LIKE ' %'").count
   (31.4ms)  SELECT COUNT(*) FROM `users` WHERE (name LIKE ' %')
=> 11
```
It's not that much but when you look for people names ending with a space, the number is kinda big:
```ruby
irb(main):011:0> User.where("name LIKE '% '").count
   (19.2ms)  SELECT COUNT(*) FROM `users` WHERE (name LIKE '% ')
=> 518
```
And those are just two simple combinations. There could be tons of users with unnecessary white characters in the name.

**Comment by larspetrus** [comment]
I think the white space issue is best solved by trimming all data as it enters the system.

A quick search found this gem: https://github.com/holli/auto_strip_attributes

What I don't like so much about it is that you have to list the fields you want stripped. I want to strip all fields.

Another approach is to always trim `params` in ApplicationController.

**Comment by jfly** [comment]
I'm going to close this in favor of #833
