### ISSUE TITLE
Discussion_url not being set

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#726]
It works great locally and at staging, but for some reason it's not working at production.
I'll change to gsub(/ /, '$20') instead of URI.encode...

**Comment by jonatanklosko** [comment]
I've caught the problem!
So before [setting discussion_url was introduced](https://github.com/cubing/worldcubeassociation.org/pull/711) there were a lot of competitions which had already their delegate reports created.
I've fixed it easily via console, see:
```ruby
irb(main):010:0> DelegateReport.where(discussion_url: nil).count
   (1.0ms)  SELECT COUNT(*) FROM `delegate_reports` WHERE `delegate_reports`.`discussion_url` IS NULL
=> 3028
irb(main):011:0> DelegateReport.where(discussion_url: nil).each do |dr|
irb(main):012:0>   dr.set_discussion_url
irb(main):013:0>   dr.save!
irb(main):014:0> end
...
irb(main):015:0> DelegateReport.where(discussion_url: nil).count
   (1.0ms)  SELECT COUNT(*) FROM `delegate_reports` WHERE `delegate_reports`.`discussion_url` IS NULL
=> 0
```

**Comment by larspetrus** [comment]
So the problem was a missing DB migration?

On Sun, Jun 26, 2016 at 7:18 AM, Jonatan Kłosko <notifications@github.com>
wrote:

> Closed #726
> <https://github.com/cubing/worldcubeassociation.org/issues/726>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cubing/worldcubeassociation.org/issues/726#event-704248802>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAuGK5zWmuh36baB8JZ1LXH56ghYXxhsks5qPopCgaJpZM4I5Thb>
> .
>



-- 
Procrastinators - the Leaders of Tomorrow

**Comment by jonatanklosko** [comment]
@larspetrus yeah I think we're used to do such things via migration. I've done this via console as it was pretty straightforward and wasn't worth separate PR I think.

**Comment by larspetrus** [comment]
Yeah, I wasn't saying you did this wrong. Mostly wondering what the root cause of the problem was.

Though, come to think of it, if someone is working on a downloaded prod DB at home, it won't get this fix.
