### ISSUE TITLE
Psych Sheet Performance

### ISSUE THREAD

**Issue by jbcm627** [cubing/worldcubeassociation.org#731]
For large competitions, psych sheets will fail to load when multiple simultaneous requests are made.
Eg, loading
https://www.worldcubeassociation.org/competitions/Euro2016/registrations/psych-sheet/333
and
https://www.worldcubeassociation.org/competitions/Euro2016/registrations/psych-sheet/pyram
Gives me a rails error after ~45 seconds:

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

For a single request (eg, Euro 3x3), page load time is ~20-25 seconds.
https://www.worldcubeassociation.org/competitions/Euro2016/registrations/psych-sheet/333

**Comment by pingskills** [comment]
Hi James,

We've now deployed a fix for this and the psych sheet should be very quick
to load. Please give it a try and let me know if it seems much better.

Regards,
Jeff.

**Comment by jbcm627** [comment]
Loads very quickly now! Thanks for the work.

Best,
Jim
