### ISSUE TITLE
Convert Virtual Models into Real Tables

### ISSUE THREAD

**Issue by pingskills** [cubing/worldcubeassociation.org#741]
The Countries, Continents, Events, Rounds, and Format models are currently virtual. Migrate these into real tables.

**Comment by pedrosino** [comment]
Not so long ago @jfly was totally against this :)
I also prefer having them as tables.

**Comment by jfly** [comment]
I did not anticipate people needed to do table joins on these things, so now I'm okay with them existing as tables.
