### ISSUE TITLE
Change How the Test Database is Loaded

### ISSUE THREAD

**Issue by pingskills** [cubing/worldcubeassociation.org#748]
As part of PR #734 there was some discussion on how the test database should be loaded. For that PR the Countries table needed to populated during tests. The database_cleaner.rb code was changed not to truncate the reference tables Countries, Continents, Events, Formats, Rounds, and teams between tests.

Before the suite runs they are truncated and loaded once with the following code:
```
  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation, except: reference_tables_to_keep)
    reference_tables_to_keep.each do |table|
      ActiveRecord::Base.connection.execute("TRUNCATE #{table};")
      load "#{Rails.root}/db/seeds/#{table.underscore}.seeds.rb"
    end
  end
```

This issue is to discuss better ways to handle this.

**Comment by jonatanklosko** [comment]
I remember Lars mentioned about creating separate class for this. [Here](https://github.com/jonatanklosko/worldcubeassociation.org/commit/ace6f4fad770b462b81b6f07f2d54d7a5c52c7ac)'s my proposition.
@larspetrus @pingskills what do you think?

**Comment by larspetrus** [comment]
At this point I'm only offended by the `load` ugliness. If there is a simple way to change it into regular code that we call in a normal way, I'd like that. If not, that's OK too.

I commented on Jonathan's proposition [over there](https://github.com/jonatanklosko/worldcubeassociation.org/commit/ace6f4fad770b462b81b6f07f2d54d7a5c52c7ac).

**Comment by pingskills** [comment]
@jonatanklosko @larspetrus 

I think we have a redundant step when using rspec. As far as I can tell this is what happens:

1. The database gets wiped
2. The seed data is loaded
3. The tables are truncated except our reference tables
4. We truncate our reference tables
5. We load our reference tables

I think we can get rid of step 2 by moving the seed files into the development directory. Does this make sense or am I missing something?

**Comment by jonatanklosko** [comment]
@pingskills interesting that I cannot see your comment again (only on email). The 2. point isn't true because if it would then we wouldn't need all the things we has been discussing for a while.

**Comment by pingskills** [comment]
@jonatanklosko yes I deleted those comments because I realised it wasn't right. I'm not sure what I was thinking :)
