### ISSUE TITLE
Make a "new post" link/button on the homepage

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#760]
We usually create posts from somewhere else (announcing competitions or results), but today I needed to make a "random" post, and couldn't find a link.

I went to /posts/new since it felt obvious because I know the website structure, but I imagine not everybody would know that.

**Comment by jonatanklosko** [comment]
It's within user's menu and I think that's fine enough. Anyway we could add a button on the home page for people with appropriate rights too.

**Comment by pedrosino** [comment]
Ah, didn't think to look there...
It's probably good enought, but I'll submit a PR if I find the time.

**Comment by jfly** [comment]
Closing, but feel free to continue this discussion over a PR.
