### ISSUE TITLE
Formal split of Board and results team memberships

### ISSUE THREAD

**Issue by SAuroux** [cubing/worldcubeassociation.org#762]
The Board and the results team have agreed on performing a formal split between Board and results team memberships. Or in other words: Board members are no longer results team members by default.

However, all Board members should still keep all permissions and access which is currently associated with a results team membership.

**Comment by jonatanklosko** [comment]
Related with #725.

**Comment by pedrosino** [comment]
For the record, I'd like to remain a results team member.

**Comment by pedrosino** [comment]
Looking through the User model, I believe the solution is very simple:

https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L341
https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L345
https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L350
https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L363
https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L367
https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L371
https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L392

All results_team? permission also include Board members. So looks like the only thing to be done here is remove the board members from the Results team, which I just did.

I'll leave this open for a day or two in case someone finds other things that need to be done.

**Comment by lgarron** [comment]
> However, all Board members should still keep all permissions and access which is currently associated with a results team membership.

Why not just make them results team members individually (if they still want to participate in results handling)?

**Comment by jfly** [comment]
@pedrosino, I believe the only thing that needs to be changed is to remove the board from [`can_admin_results?`](https://github.com/cubing/worldcubeassociation.org/blob/bad53e5988e752f8a08722ef915ddc552da1619f/WcaOnRails/app/models/user.rb#L345). All the other ones look like permissions we want the board to continue to have.

**Comment by jfly** [comment]
@pedrosino, I've assigned this to you. Please feel free to unassign yourself if you don't have time to work on it.

**Comment by pedrosino** [comment]
I'm not sure I understand. can_admin_results? is exactly what we want Board members to keep:
> However, all Board members should still keep all permissions and access which is currently associated with a results team membership.

**Comment by jfly** [comment]
Then, as Lucas said, we should mark each board member as a member of the results team.

**Comment by pedrosino** [comment]
That seems to work too, but feels more troublesome. We'd also have people listed under the results team which are not really part of the team.

**Comment by jfly** [comment]
I don't understand what this issue is about, then. @SAuroux, can you explain what exactly the results team and the board agreed upon?

**Comment by SAuroux** [comment]
It is very simple actually. We agreed to only list those people as results
team members who commit themselves to regularly perform results team tasks.
All other Board members however should still have access to the database
and to the results team scripts.

I am not familiar with how this access is arranged on the website. If the
Board membership alone already provides this access, then this is a
non-issue.

Am 12.07.2016 16:30 schrieb "Jeremy Fleischman" <notifications@github.com>:

**Comment by jfly** [comment]
I see. This is a non-issue, then, as board members are included in the [`can_admin_results?`](https://github.com/cubing/worldcubeassociation.org/blob/bad53e5988e752f8a08722ef915ddc552da1619f/WcaOnRails/app/models/user.rb#L345) method.
