### ISSUE TITLE
Map in competition tabs doesn't work

### ISSUE THREAD

**Issue by MatteoColombo** [cubing/worldcubeassociation.org#763]
I was trying the new competition tab feature (which is really cool :D) and I noticed that the insert Map option doesn't work.

I tried with both the coordinates and the address and none of them works.

Here is an example with the Milan Summer Open 2016:
https://www.worldcubeassociation.org/competitions/MilanSummerOpen2016#5-venue

**Comment by jonatanklosko** [comment]
Hi,

Thanks for reporting, it works fine now!

Cheers,
Jonatan

2016-07-06 16:11 GMT+02:00 Matteo <notifications@github.com>:
