### ISSUE TITLE
Access WCA profile easily when signed in

### ISSUE THREAD

**Issue by jonatanklosko** [cubing/worldcubeassociation.org#771]
It should be simplified so that when you are signed in, it's sufficient to do like 1 or 2 clicks to access your WCA profile.
Sébastien asked for this.
Note (obvious but should avoid potential error): not every user has WCA id.

**Comment by viroulep** [comment]
Couldn't we simply add a "My results" link to the "Results" menu (under "Persons")?

**Comment by jonatanklosko** [comment]
@viroulep I think this would correspond to "My competitions" pretty nicely.

**Comment by viroulep** [comment]
You mean a link on the "My competitions" page?

**Comment by jonatanklosko** [comment]
I mean the link to "My competitions" page. I just think this is good idea to have "My results" in the "Results" menu the same way we have "My competitions" in the "Competitions" menu =)
