### ISSUE TITLE
Add Liechtenstein to countries

### ISSUE THREAD

**Issue by jonatanklosko** [cubing/worldcubeassociation.org#773]
This requires adding Liechtenstein's data in three places:
- Country model (country.rb)
- Seeds file (db/seeds/countries.seeds.rb)
- A migration to insert Liechtenstein to the countries table (the same addition as in the seeds file)

After deploy we just need to run the migration.

**Comment by pedrosino** [comment]
I thought we moved countries to the countries table sometime ago?

**Comment by jonatanklosko** [comment]
It's part of #759, until it's merged we need to update country.rb as well.
