### ISSUE TITLE
Consider another map service

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#79]
https://www.worldcubeassociation.org/results/competitions.php?eventId=&regionId=&years=current&pattern=&map=Map

It uses an external JS file via HTTP, which causes an HTTPS warning. So, either find an HTTPS URL we can point to, or host it on our server.

**Comment by gagou9** [comment]
These are the faulty files : 
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m1.png
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m2.png

It should be fixed by 590b478dcf11e98bbefa8022e9e6b491267a61f9

**Comment by gagou9** [comment]
As this is in wca-website-php, it has not been merged into production branch. I have no idea how to do that!

**Comment by jfly** [comment]
You need to update the submodule after you change the wca-website-php repo. Did https://github.com/cubing/worldcubeassociation.org/commit/f6688361c1a2d5ebe4c29789b533ff9c85250696 pull in your changes?

**Comment by gagou9** [comment]
Nope, the file on the server is still without https !
I don't know how to update the submodule by the way. How should I do?
thanks!

**Comment by jfly** [comment]
It's quite annoying. I think `git submodule foreach git pull` followed by a `git commit` might do it.

To isolate the problem, lets ignore what's on the server. If you do a fresh `git clone --recursive git@github.com:cubing/worldcubeassociation.org.git`, do you end up with the correct file?

**Comment by gagou9** [comment]
@jfly do you mean running that "git clone --recursive [...]" on the production server? no?

I'm currently provisioning my local WCA VM, hopefully it works and I can go further on my jobs :)

**Comment by jfly** [comment]
I meant run that command in a local checkout. If it pulls in anything new, you'll have to commit. Might be best to talk about this in real time =)
