### ISSUE TITLE
Regs History says 2009 did not have regs, but they do?

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#800]
https://www.worldcubeassociation.org/regulations/history/ states "No new Regulations" for 2009.

But I just realized https://www.worldcubeassociation.org/regulations/history/files/regulations2009.html does exist. It introduced certain new scramble programs.

@Laura-O for WRC visibility.

**Comment by viroulep** [comment]
@cubing/wrc-team ;)
I'll fix this.

I also noticed the 2015 history link points to the current Regulations, and we are missing a "current version" link :p

**Comment by viroulep** [comment]
Fixed by #805.
