### ISSUE TITLE
Complete removeUglyAccentsAndStuff

### ISSUE THREAD

**Issue by Luis-J-Ianez** [cubing/worldcubeassociation.org#82]
Strings defined in `removeUglyAccentsAndStuff` inside [persons_finish_unfinished.php](https://github.com/cubing/worldcubeassociation.org/blob/cfb9a3967eef969426148e5fcc4a0995ef773d4c/webroot/results/admin/persons_finish_unfinished.php#L233) should be completed.  Examples of unsupported usual characters: 'Ł', 'Ż' and their lower cases.  I will complete the list if I happen to find more cases.

**Comment by jfly** [comment]
When we port the administration scripts to rails, we can use the [transliterate](http://apidock.com/rails/ActiveSupport/Inflector/transliterate) method to do this.

**Comment by jfly** [comment]
This is being addressed by @Luis-J-Ianez's changes in https://github.com/cubing/worldcubeassociation.org/pull/208/files#diff-30ef4de1f7b561690b08fa73914ae444R144.
