### ISSUE TITLE
Page with information about delegates

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#836]
From Ilkyoo:
>Can we get a list of delegates, sorted by their recent delegated comp?
>The fields would be
>delegate / position / country / last delegated date

From Ron:
>I find this interesting. In addition I would love to see much more statistical information.
>Example:
>First, last, number of competitions:
>per delegate, country, continent, organizer, member

I'm focusing on the delegate's part for now.

**Comment by jfly** [comment]
Do we really need this? These are easy SQL commands, and I'd rather not have to support a new page if we can avoid it.

@pedrosino, can we close this in favor of #137?

**Comment by pedrosino** [comment]
Not sure where this should be, though.
/delegates is a static_page, but looks like the one that makes more sense. Maybe having a switch of some sort to access the "admin view" would work.

EDIT

Ilkyoo requested this again, and I think it would be ok to have it. Not everybody is good with SQL queries, and having a page gives the ability to sort and search and etc.

**Comment by Ilkyoo** [comment]
The word easy is different from easily accessible.

**Comment by pedrosino** [comment]
I am actually working on this already.
