### ISSUE TITLE
Inclusing delegate reports

### ISSUE THREAD

**Issue by jonatanklosko** [cubing/worldcubeassociation.org#837]
Just stumbled upon very weird thing with @pedrosino when playing with his PR on the staging.
Issue example:
```ruby
Competition.includes(:delegate_report).each do |competition|
  puts competition.delegate_report.created_at
end
```
I guess no one would expect this to do additional query for each competition ... but it does!
After some struggling with this I finally realised that `competition.delegate_report` doesn't actually call the relation, see how this method is overridden [here](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition.rb#L630-L635).
Now it appears that the implementation isn't as well as we thought.

I think that it doesn't make difference whether we create the report when it's first called or just when a competition is created, so here's my proposal:
```ruby
# This method is generated by Rails automatically for one-to-one relations =)
after_create :create_delegate_report

# Remove overridden delegate_report method.
```
I think that it's cleaner, less error prone and allows us to call `includes` happily!
What do you think?

**Comment by pedrosino** [comment]
Good catch!
I like the solution, seems easier than what we have now.
