### ISSUE TITLE
Add search box to /users

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#84]
Right now it's rather difficult to find a user (the pagination is pretty annoying).

**Comment by lgarron** [comment]
The fields look like they are made meant for adding a user, not for search, and the action icons in the last column don't have have a hover title.
Would it be easy to use a magnifying class icon, or something like that.

**Comment by jfly** [comment]
These are just the defaults from https://github.com/leikind/wice_grid. There is definitely room for improvement. Styling is pretty low on my list of priorities right now. I'm really hoping to do a poor enough job that someone like you steps in and styles things =)
