### ISSUE TITLE
bundle install when deploying oftentimes runs into permission errors

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#840]
Some analysis by @viroulep:

---
Hum if the first `bundle install` ever was done without argument, the default behavior is to install system-wide (and this setup is remembered for the next calls to bundle), and it seems to be the case:

```
~ @production> cat worldcubeassociation.org/WcaOnRails/.bundle/config 
...
BUNDLE_WITHOUT: none
 ~/worldcubeassociation.org/WcaOnRails @production> bundle show rails
/var/lib/gems/2.3.0/gems/rails-4.2.1
```

On my computer I ran the first 'bundle install' with '--path vendor/bundle' and it shows up in the config :
```
[15:36] daisy:~/Documents/cube/wca/worldcubeassociation.org/WcaOnRails (i18n↑1|✚1…)$ cat .bundle/config 
...
BUNDLE_WITHOUT: none
BUNDLE_PATH: vendor/bundle
BUNDLE_DISABLE_SHARED_GEMS: true
[15:36] daisy:~/Documents/cube/wca/worldcubeassociation.org/WcaOnRails (i18n↑1|✚1…)$ bundle show rails
/home/fifi/Documents/cube/wca/worldcubeassociation.org/WcaOnRails/vendor/bundle/ruby/2.3.0/gems/rails-4.2.1
```

So if the issue keeps happening every time we install new gems, maybe it's because the first 'bundle install' succeeds to install system-wide.
If i'm not mistaken it's run for the first time by the chef script [here](https://github.com/cubing/worldcubeassociation.org/blob/8371f801fe83502b23b39272ae58d148d3b2b2f2/chef/site-cookbooks/wca/recipes/default.rb#L326-L331), any chance this part may be run as root or with sudo?
IIRC, if bundle tries to install to system he may ask for sudo password.

I don't have the knowledge about the standard setup for rails applications on production, but the two options I see are:
- Run the first 'bundle install' as 'cubing' with a custom path which does not require root permission, and change nothing in the deployment process.
- Run all 'bundle install' to system, which means if new gems have been added you have to sudo

I like 1 because it's pretty simple and deploys without sudo, but again I don't know what is done "usually" for production.

---

I (@jfly) also like solution 1 from @viroulep.

**Comment by jfly** [comment]
@viroulep, I've assigned this to you. If you're too busy to work on this, no worries, just unassign it and I'll find someone else to take it on!

**Comment by viroulep** [comment]
I have internet at home again so worst case scenario I can take care of this on Saturday or Sunday.

This is independent from #747 but both will need the timely operation of spinning up a new server; maybe both could be confirmed to work at the same time?

**Comment by viroulep** [comment]
I took a look at [that](http://bundler.io/man/bundle-install.1.html#DEPLOYMENT-MODE), looks like installing in a custom location is part of what bundle does in deployment mode :)

So the fix may be as simple as running `bundle install --deployment --without none` as cubing, but I'm concerned about using this flag for provisioning the VM in development mode...
@jfly how did you test the production-only parts of the chef scripts?


Btw we definitely run [this](https://github.com/cubing/worldcubeassociation.org/blob/8371f801fe83502b23b39272ae58d148d3b2b2f2/chef/site-cookbooks/wca/recipes/default.rb#L326-L331) as root!

I tried to spin up a VM with that:
```ruby
#### Initialize rails gems/database
execute "bundle install --without none" do
  user username #<- change here!
  cwd rails_root
  environment({
    "RACK_ENV" => rails_env,
  })
end
```

And ran into this error:
>================================================================================
==> noregs: Error executing action `run` on resource 'execute[bundle install --without none]'
==> noregs: ================================================================================
==> noregs: Mixlib::ShellOut::ShellCommandFailed
==> noregs: ------------------------------------
==> noregs: Expected process to exit with [0], but received '23'
==> noregs: ---- Begin output of bundle install --without none ----
==> noregs: 
==> noregs: STDOUT: Fetching gem metadata from https://rails-assets.org/...
[...]
==> noregs: 
==> noregs: There was an error while trying to write to `/root/.bundle/cache/git`. It is
==> noregs: 
==> noregs: likely that you need to grant write permissions for that path.
==> noregs: 
==> noregs: STDERR: 
==> noregs: 
==> noregs: ---- End output of bundle install --without none ----
==> noregs: 
==> noregs: Ran bundle install --without none returned 23

So the default user for running `execute` block in chef is root, hence all the issues when updating gems :)

**Comment by jfly** [comment]
Awesome investigation, @viroulep! I'm glad to finally know the source of this issue =) It threw me off that subsequent `bundle install` runs by non root users usually work, until there's a new gem to install.

> @jfly how did you test the production-only parts of the chef scripts?

I spin up a new server in production mode =). I used to do this with Vagrant, but nowadays, I just spin up a new server on AWS. If you want to test things out with Vagrant, you'll need to tweak our [Vagrantfile](https://github.com/cubing/worldcubeassociation.org/blob/66a9530b6ab0e6dd23839a3f552862901363243c/Vagrantfile#L13-L27) to pass `production` to [wca-bootstrap.sh](https://github.com/cubing/worldcubeassociation.org/blob/ab67fb21a55ef5a7fc891f94070af26d5cec9b58/scripts/wca-bootstrap.sh#L20).

**Comment by viroulep** [comment]
>  If you want to test things out with Vagrant, you'll need to tweak our Vagrantfile to pass production to wca-bootstrap.sh.

Ok thanks :)
