### ISSUE TITLE
Login with WCA id

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#85]
In addition to logging in with email =)

**Comment by Alukret** [comment]
I think 99% of competitors do not remember their WCA id's. Do we really 
need this?

-Roman

**Comment by FatBoyXPC** [comment]
2010LACH01 - I sure do :) @jfly is 2005FLEI01 I believe, and I know several of my friends, as well :P

**Comment by jfly** [comment]
I usually agree with "don't do something unless we really need it", but this seems simple enough that there's no downside.
