### ISSUE TITLE
Improvements to competitions?display=admin

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#862]
From Ilkyoo:
>I don’t like “past” because I don’t necessarily want to see all comps in 2016, I just want to see comps within the last 30 days.
>So making a “recent” button that only displays comps in the last 30 days would be better. 

>Also, having a button that shows comps that are missing reports and/or results would be good. 

- [x] "recent" button
- missing reports/results can be complicated, because we have flaws in the database. However, we could set a starting point to this (2016?)
- [x] I thought of having "missing stuff" information on the table, like showing how many days have passed since the competition if results/reports are not posted yet. It would work almost the same way, except for doing (today - comp_date) instead of (results_posted - comp_date), and we could use the same colors, but with something to show that those are still pending.

**Comment by Ilkyoo** [comment]
-- A button that displays comps with at least one red cell 
-- A button that displays comps with at least one red cell or one yellow cell 

These two buttons would be useful too.

**Comment by pedrosino** [comment]
I just thought that clicking "Past from 2016" will open the "recent" list as the first thing. The only moment this doesn't work is january of each year, when you'll either get competitions from that year (choosing "past from 2017", for example) or from the previous year (choosing "past from 2016").

Maybe this is something other people would be interested in as well? Seeing results for competitions in the last month.
I'll try to implement it.

**Comment by pedrosino** [comment]
Here are 2 options for showing "pending" results/report:
![pending](https://cloud.githubusercontent.com/assets/1881933/18395274/53943c70-7694-11e6-894c-119cbcaddd83.png)

I think I prefer the one to the right (not showing how many days have passed)
