### ISSUE TITLE
Continent model is built with no `recordName`

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#871]
The `Continent` constructor [here](https://github.com/cubing/worldcubeassociation.org/blob/fa94cab57ffd9528092c1e9930cefb57d4b739e1/WcaOnRails/app/models/continent.rb#L8) gets the `recordName` attribute from the  `continentId`, which does not exist in the hashes we give [here](https://github.com/cubing/worldcubeassociation.org/blob/fa94cab57ffd9528092c1e9930cefb57d4b739e1/WcaOnRails/app/models/continent.rb#L38-L87) (meaning `continent.recordName` is nil).

I'll fix this since I'm i18n-ing this part.
(unless it's not a bug :p)

**Comment by jfly** [comment]
Definitely looks like a bug. CC-ing @pingskills because of his pending work on #741 (pr #759).

**Comment by viroulep** [comment]
This has actually been fixed by @pingskills in #759 ;)
