### ISSUE TITLE
poll.rb is ignoring `marked_for_destruction`

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#883]
See discussion [here](https://github.com/cubing/worldcubeassociation.org/pull/759/files/092c6c899303fd543fc8b55597e4fb8ebc2c16fe#r78271394) and [here](http://homeonrails.com/2012/10/validating-nested-associations-in-rails/).

Adding the following test to `poll_spec.rb` fails:

```ruby
    it "cannot remove poll options on a confirmed poll" do
      poll = FactoryGirl.create :poll
      FactoryGirl.create(:poll_option, poll_id: poll.id)
      FactoryGirl.create(:poll_option, poll_id: poll.id)
      poll.confirmed = true
      expect(poll).to be_valid
    
      poll.poll_options[0].mark_for_destruction
      poll.poll_options[1].mark_for_destruction
      expect(poll).to be_invalid
    end
```

**Comment by jfly** [comment]
@pedrosino, I've assigned this to you as this is code you're familiar with =)

**Comment by pedrosino** [comment]
The first discussion link doesn't work anymore.

From what I remember, we validate this on confirming a poll. I just tried and it works as expected.
Except if you create two options, then update, then remove one of them and click confirm, without updating again. The validation will pass and the poll will be confirmed with only one option :P

@jonatanklosko found out that simply adding .reject(&:marked_for_destruction?) to the self.poll_options before getting the length does the trick.
