### ISSUE TITLE
Dead code in users.js(?)

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#900]
When looking for string to localize in js files (#816), I noticed [this](https://github.com/cubing/worldcubeassociation.org/blob/9f1b0c44fefb7927860f8e88cf9a1023b05cba52/WcaOnRails/app/assets/javascripts/users.js#L52-L64) code block.
It was introduced by @jonatanklosko in #466, and the screenshot displays both strings defined in the code block ("Showing i of N rows blahblah").

However when visiting `users#index` this line of information is not displayed anymore. The code block *is* executed, and the table has the `bs-table` class, so I assume there must be some bootstrap-table option to hide this information line: I think either we need to activate this option to display the line, or get rid of this unused code block.

I did not go through all the discussions on the PR because it may have been deactivated later, @jonatanklosko could you clarify what is the intended behavior?

**Comment by jonatanklosko** [comment]
@viroulep good catch =) I've looked into this and found out that a CSS rule has been affecting the page accidentally. Then the fix was straightforward.

**Comment by viroulep** [comment]
Thanks!
