### ISSUE TITLE
Venue in the competition list not wrapping properly when it is long

### ISSUE THREAD

**Issue by oyyq99999** [cubing/worldcubeassociation.org#911]
![image](https://cloud.githubusercontent.com/assets/3143564/18806295/1472d3d0-825b-11e6-8bf8-d84bd5cb5062.png)
It looks strange to have some words under the date.

**Comment by jfly** [comment]
This is intentional. Feel free to send in a PR with a change if you have something better in mind, but I'm going to close this!
