### ISSUE TITLE
WRC Announcement Links are broken

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#97]
https://www.worldcubeassociation.org/regulations/announcements/
https://www.worldcubeassociation.org/regulations/history/ > Summarized Changes

**Comment by lgarron** [comment]
Most of them are here: https://github.com/cubing/wca-documents-extra/tree/master/announcements

**Comment by lgarron** [comment]
Example: for by @KitClement:

The 2014-01-01 Regulations announcement is at https://www.worldcubeassociation.org/?page=50 t the moment, but clicking on it takes you to https://www.worldcubeassociation.org/posts/2014-01-01 (which shows the wrong post).

**Comment by jfly** [comment]
Fixed. There is no https://www.worldcubeassociation.org/regulations/announcements/ page anymore. Our posts are dead simple, and there is no concept of tagging. If you need a list of regulations posts, it will be up to the regulations team to keep track of your own posts. If that's too much of a hassle, I will accept a PR adding a bit to the db schema to differentiate regulations posts from competition results and announcements, but it is not a priority right now.

**Comment by Laura-O** [comment]
There's still a link to the announcements page in the dropdown menu. This should be removed as well.

**Comment by jfly** [comment]
Good point. Thanks, @Laura-O!
