### ISSUE TITLE
Posts do not have a shortened preview on the front page

### ISSUE THREAD

**Issue by lgarron** [cubing/worldcubeassociation.org#99]
https://www.worldcubeassociation.org/posts/wca-regulations-july-2015 takes up all of https://www.worldcubeassociation.org/ right now. We're planning to have that announcement up for at least two weeks, during which it pushes away important announcements for Worlds and Nationals (and hides the regular dynamic content even more).

In Drupal, it was possible to insert a divider. The short preview (shown on the front page) was truncated at the divider, with a link to see more. For example, see `<!--break-->` [here](https://raw.githubusercontent.com/cubing/wca-documents-extra/master/announcements/official-2014-01-01.md).

**Comment by jfly** [comment]
This should be a good project for someone to get started with.
